"""
Integration tests for sam local invoke with CloudFormation Language Extensions.

Tests verify that sam local invoke can invoke functions generated by Fn::ForEach
expansion from templates using AWS::LanguageExtensions transform.

Requirements:
- 4.1: WHEN `sam local invoke` is called with an expanded function name (e.g., `AlphaFunction`),
       THE Local_Invoke_Command SHALL invoke that specific function
- 12.2: THE Integration_Tests SHALL verify `sam local invoke` can invoke expanded functions
        by their generated names
"""

import os
import shutil
import sys
import tempfile
import uuid
from pathlib import Path

import pytest

from tests.integration.local.invoke.invoke_integ_base import InvokeIntegBase
from tests.testing_utils import get_sam_command, run_command


class TestInvokeLanguageExtensions(InvokeIntegBase):
    """
    Integration tests for sam local invoke with CloudFormation Language Extensions.

    This test class verifies that functions generated by Fn::ForEach expansion
    can be invoked using sam local invoke with their expanded names.
    """

    template_subdir = "buildcmd"

    def setUp(self):
        """Set up test fixtures with a scratch directory for build artifacts."""
        # Use a scratch directory within the test folder (similar to build tests)
        # This ensures Docker can access the built artifacts
        self.scratch_dir = str(Path(__file__).resolve().parent.joinpath("tmp", str(uuid.uuid4()).replace("-", "")[:10]))
        shutil.rmtree(self.scratch_dir, ignore_errors=True)
        os.makedirs(self.scratch_dir)

        self.working_dir = tempfile.mkdtemp(dir=self.scratch_dir)
        self.build_dir = Path(self.working_dir, ".aws-sam", "build")
        self.built_template_path = self.build_dir.joinpath("template.yaml")

        # Use the original template path (not copied)
        self.template_path = Path(self.test_data_path, "buildcmd", "language-extensions.yaml")

    def tearDown(self):
        """Clean up scratch directory after test."""
        try:
            shutil.rmtree(self.scratch_dir, ignore_errors=True)
        except Exception:
            pass

    def _get_python_version(self):
        """Get the current Python version in the format expected by Lambda runtimes."""
        return f"python{sys.version_info.major}.{sys.version_info.minor}"

    def _make_parameter_override_arg(self, overrides):
        """Create parameter override argument string."""
        return " ".join([f"ParameterKey={key},ParameterValue={value}" for key, value in overrides.items()])

    @pytest.mark.flaky(reruns=3)
    def test_invoke_foreach_expanded_alpha_function(self):
        """
        Test invoking AlphaFunction from ForEach-expanded template.

        This test verifies:
        1. sam build successfully builds the language extensions template
        2. sam local invoke can invoke AlphaFunction (generated by Fn::ForEach)
        3. The function executes successfully (exit code 0)
        4. The output contains expected response

        Validates: Requirements 4.1, 12.2
        """
        # Use the current Python version for the runtime to avoid version mismatch
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Build the template
        build_command = [
            get_sam_command(),
            "build",
            "-t",
            str(self.template_path),
            "-b",
            str(self.build_dir),
            "--parameter-overrides",
            self._make_parameter_override_arg(overrides),
        ]

        build_result = run_command(build_command, cwd=self.working_dir)

        self.assertEqual(
            build_result.process.returncode,
            0,
            f"sam build should succeed for language extensions template. stderr: {build_result.stderr.decode('utf-8')}",
        )

        # Verify the built template exists
        self.assertTrue(
            self.built_template_path.exists(),
            f"Built template should exist at {self.built_template_path}",
        )

        # Verify AlphaFunction directory was created in build output
        alpha_function_dir = self.build_dir.joinpath("AlphaFunction")
        self.assertTrue(
            alpha_function_dir.exists(),
            f"AlphaFunction build artifacts should exist at {alpha_function_dir}",
        )

        # Invoke AlphaFunction using the built template
        invoke_command = self.get_command_list(
            function_to_invoke="AlphaFunction",
            template_path=str(self.built_template_path),
            no_event=True,
        )
        stdout, stderr, invoke_exit_code = self.run_command(invoke_command, cwd=self.working_dir)

        # Verify the function executed successfully
        self.assertEqual(
            invoke_exit_code,
            0,
            f"sam local invoke AlphaFunction should succeed. stdout: {stdout}, stderr: {stderr}",
        )

        # Verify the output contains expected response from the handler
        # The handler returns "Hello World"
        process_stdout = stdout.strip().decode("utf-8")
        self.assertIn("Hello World", process_stdout, "Output should contain 'Hello World' from the handler response")

    @pytest.mark.flaky(reruns=3)
    def test_invoke_config_function(self):
        """
        Test invoking ConfigFunction from a template with language extensions.

        This test verifies that a regular function (not generated by ForEach)
        in a template that uses AWS::LanguageExtensions can be invoked successfully.

        Validates: Requirements 4.1, 12.2
        """
        # Use the current Python version for the runtime to avoid version mismatch
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Build the template
        build_command = [
            get_sam_command(),
            "build",
            "-t",
            str(self.template_path),
            "-b",
            str(self.build_dir),
            "--parameter-overrides",
            self._make_parameter_override_arg(overrides),
        ]

        build_result = run_command(build_command, cwd=self.working_dir)

        self.assertEqual(
            build_result.process.returncode,
            0,
            f"sam build should succeed for language extensions template. stderr: {build_result.stderr.decode('utf-8')}",
        )

        # Invoke ConfigFunction (a regular function in the template)
        invoke_command = self.get_command_list(
            function_to_invoke="ConfigFunction",
            template_path=str(self.built_template_path),
            no_event=True,
        )
        stdout, stderr, invoke_exit_code = self.run_command(invoke_command, cwd=self.working_dir)

        # Verify the function executed successfully
        self.assertEqual(
            invoke_exit_code,
            0,
            f"sam local invoke ConfigFunction should succeed. stderr: {stderr}",
        )

        # Verify the output contains expected response from the handler
        # The handler returns "Hello World"
        process_stdout = stdout.strip().decode("utf-8")
        self.assertIn("Hello World", process_stdout, "Output should contain 'Hello World' from the handler response")

    @pytest.mark.flaky(reruns=3)
    def test_invoke_foreach_expanded_beta_function(self):
        """
        Test invoking BetaFunction from ForEach-expanded template.

        This test verifies that a different function generated by the same
        Fn::ForEach loop can also be invoked successfully.

        Validates: Requirements 4.1, 12.2
        """
        # Use the current Python version for the runtime to avoid version mismatch
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Build the template
        build_command = [
            get_sam_command(),
            "build",
            "-t",
            str(self.template_path),
            "-b",
            str(self.build_dir),
            "--parameter-overrides",
            self._make_parameter_override_arg(overrides),
        ]

        build_result = run_command(build_command, cwd=self.working_dir)

        self.assertEqual(
            build_result.process.returncode,
            0,
            f"sam build should succeed for language extensions template. stderr: {build_result.stderr.decode('utf-8')}",
        )

        # Verify BetaFunction directory was created in build output
        beta_function_dir = self.build_dir.joinpath("BetaFunction")
        self.assertTrue(
            beta_function_dir.exists(),
            f"BetaFunction build artifacts should exist at {beta_function_dir}",
        )

        # Invoke BetaFunction using the built template
        invoke_command = self.get_command_list(
            function_to_invoke="BetaFunction",
            template_path=str(self.built_template_path),
            no_event=True,
        )
        stdout, stderr, invoke_exit_code = self.run_command(invoke_command, cwd=self.working_dir)

        # Verify the function executed successfully
        self.assertEqual(
            invoke_exit_code,
            0,
            f"sam local invoke BetaFunction should succeed. stdout: {stdout}, stderr: {stderr}",
        )

        # Verify the output contains expected response from the handler
        # The handler returns "Hello World"
        process_stdout = stdout.strip().decode("utf-8")
        self.assertIn("Hello World", process_stdout, "Output should contain 'Hello World' from the handler response")
