"""
Integration tests for sam local invoke with CloudFormation Language Extensions.

Tests that sam local invoke can invoke functions generated by Fn::ForEach expansion.
"""

import os
import shutil
import sys
import tempfile
import uuid
from pathlib import Path

import pytest

from tests.integration.local.invoke.invoke_integ_base import InvokeIntegBase
from tests.testing_utils import get_sam_command, run_command


class TestInvokeLanguageExtensions(InvokeIntegBase):
    """Integration tests for sam local invoke with Fn::ForEach-expanded functions."""

    template_subdir = "buildcmd"

    def setUp(self):
        self.scratch_dir = str(Path(__file__).resolve().parent.joinpath("tmp", str(uuid.uuid4()).replace("-", "")[:10]))
        shutil.rmtree(self.scratch_dir, ignore_errors=True)
        os.makedirs(self.scratch_dir)

        self.working_dir = tempfile.mkdtemp(dir=self.scratch_dir)
        self.build_dir = Path(self.working_dir, ".aws-sam", "build")
        self.built_template_path = self.build_dir.joinpath("template.yaml")
        self.template_path = Path(self.test_data_path, "buildcmd", "language-extensions.yaml")

    def tearDown(self):
        shutil.rmtree(self.scratch_dir, ignore_errors=True)

    def _get_python_version(self):
        return f"python{sys.version_info.major}.{sys.version_info.minor}"

    def _make_parameter_override_arg(self, overrides):
        return " ".join([f"ParameterKey={key},ParameterValue={value}" for key, value in overrides.items()])

    @pytest.mark.tier1_extra
    @pytest.mark.tier1_extra
    @pytest.mark.flaky(reruns=3)
    def test_invoke_foreach_expanded_function(self):
        """Test invoking a function generated by Fn::ForEach expansion."""
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        build_command = [
            get_sam_command(),
            "build",
            "-t",
            str(self.template_path),
            "-b",
            str(self.build_dir),
            "--parameter-overrides",
            self._make_parameter_override_arg(overrides),
        ]

        build_result = run_command(build_command, cwd=self.working_dir)
        self.assertEqual(
            build_result.process.returncode,
            0,
            f"sam build failed: {build_result.stderr.decode('utf-8')}",
        )

        self.assertTrue(self.built_template_path.exists())
        self.assertTrue(self.build_dir.joinpath("AlphaFunction").exists())

        invoke_command = self.get_command_list(
            function_to_invoke="AlphaFunction",
            template_path=str(self.built_template_path),
            no_event=True,
        )
        stdout, stderr, invoke_exit_code = self.run_command(invoke_command, cwd=self.working_dir)

        self.assertEqual(invoke_exit_code, 0, f"invoke failed: stdout={stdout}, stderr={stderr}")
        self.assertIn("Hello World", stdout.strip().decode("utf-8"))
