version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope
    reviewers:
      - aws/serverless-application-experience-sbt
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: chore
      include: scope
    reviewers:
      -  aws/serverless-application-experience-sbt
    open-pull-requests-limit: 10
    ignore:
      # Ignored intentionally since we have a GHA that updates to more
      # completely
      - dependency-name: "aws-sam-translator"
      # Ignored intentionally since we have a GHA that updates to more
      # completely
      - dependency-name: "aws_lambda_builders"
      # The dependencies are intentionally pinned to certain
      # version ranges for specific Python versions
      - dependency-name: "flake8"
      - dependency-name: "isort"
