"""
Integration tests for sam package with CloudFormation Language Extensions.

These tests verify that sam package correctly processes templates using
AWS::LanguageExtensions transform, including Fn::ForEach with static and dynamic CodeUri.

Requirements tested:
- 4.2: sam package uploads each artifact to S3 with unique content-based hash key
- 4.3: sam package generates Mappings section for dynamic artifact properties
- 4.4: sam package replaces dynamic artifact property with Fn::FindInMap
- 4.5: sam package preserves Fn::ForEach structure (not expand to individual resources)
- 4.6: Generated Mappings section name follows pattern SAM{PropertyName}{LoopName}
- 4.8: sam package emits warning for parameter-based collection with dynamic CodeUri
- 13.1: sam package uploads shared artifact once for Fn::ForEach with static CodeUri
- 13.2: sam package preserves Fn::ForEach structure in packaged template
- 13.3: S3 URI is the same for all functions generated by Fn::ForEach with static CodeUri
- 16.7: Integration tests verify sam package preserves Fn::ForEach structure
"""

import json
import os
import re
import tempfile
from pathlib import Path
from subprocess import Popen, PIPE, TimeoutExpired
from unittest import skipIf

from samcli.yamlhelper import yaml_parse

from .package_integ_base import PackageIntegBase
from tests.testing_utils import RUNNING_ON_CI, RUNNING_TEST_FOR_MASTER_ON_CI, RUN_BY_CANARY

# Package tests require credentials and CI/CD will only add credentials to the env if the PR is from the same repo.
# This is to restrict package tests to run outside of CI/CD, when the branch is not master and tests are not run by Canary.
SKIP_PACKAGE_TESTS = RUNNING_ON_CI and RUNNING_TEST_FOR_MASTER_ON_CI and not RUN_BY_CANARY
TIMEOUT = 300


@skipIf(SKIP_PACKAGE_TESTS, "Skip package tests in CI/CD only")
class TestPackageLanguageExtensions(PackageIntegBase):
    """
    Integration tests for sam package with CloudFormation Language Extensions.

    Tests that sam package correctly processes templates with:
    - Fn::ForEach generating multiple Lambda functions with static CodeUri
    - Fn::ForEach generating multiple Lambda functions with dynamic CodeUri
    - Preservation of Fn::ForEach structure in packaged template
    - Same S3 URI for all functions with static CodeUri
    - Generated Mappings section for dynamic CodeUri
    - Fn::FindInMap replacement for dynamic artifact properties
    - Unique content-based S3 keys for each artifact

    Validates Requirements: 4.2, 4.3, 4.4, 4.5, 4.6, 4.8, 13.1, 13.2, 13.3, 16.7
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        # Override test_data_path to point to the language extensions test data
        cls.test_data_path = Path(__file__).resolve().parents[1].joinpath("testdata", "package")

    def test_package_preserves_foreach_structure_with_static_codeuri(self):
        """
        Test that sam package preserves Fn::ForEach structure with static CodeUri.

        This test verifies:
        1. Package succeeds with language extensions template
        2. Packaged template preserves the Fn::ForEach structure
        3. S3 URI is the same for all functions generated by Fn::ForEach
        4. The shared artifact is uploaded once

        Validates Requirements: 13.1, 13.2, 13.3, 16.7
        """
        template_path = self.test_data_path.joinpath("language-extensions-foreach", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            process_stdout = stdout.strip().decode("utf-8")
            process_stderr = stderr.strip().decode("utf-8")

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stdout: {process_stdout}, stderr: {process_stderr}",
            )

            # Verify success message
            self.assertIn(
                f"Successfully packaged artifacts and wrote output template to file {output_template.name}",
                process_stdout,
            )

            # Read the packaged template using SAM CLI's YAML parser
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Requirement 13.2, 16.7: Verify Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Functions"

            self.assertIn(
                foreach_key,
                resources,
                f"Packaged template should preserve {foreach_key} structure",
            )

            # Verify the Fn::ForEach structure is correct
            foreach_block = resources[foreach_key]
            self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
            self.assertEqual(
                len(foreach_block),
                3,
                "Fn::ForEach block should have 3 elements: variable, collection, body",
            )

            # Verify the loop variable
            loop_variable = foreach_block[0]
            self.assertEqual(loop_variable, "FunctionName", "Loop variable should be 'FunctionName'")

            # Verify the collection
            collection = foreach_block[1]
            self.assertIsInstance(collection, list, "Collection should be a list")
            self.assertEqual(collection, ["Alpha", "Beta"], "Collection should contain ['Alpha', 'Beta']")

            # Verify the body template contains the function definition
            body_template = foreach_block[2]
            self.assertIsInstance(body_template, dict, "Body template should be a dict")
            self.assertIn("${FunctionName}Function", body_template, "Body should contain function template")

            # Verify the function template structure
            function_template = body_template["${FunctionName}Function"]
            self.assertEqual(
                function_template.get("Type"),
                "AWS::Serverless::Function",
                "Function template should have correct Type",
            )

            # Requirement 13.3: Verify CodeUri is updated to S3 URI
            properties = function_template.get("Properties", {})
            code_uri = properties.get("CodeUri")

            self.assertIsNotNone(code_uri, "CodeUri should be present in function template")
            self.assertIsInstance(code_uri, str, "CodeUri should be a string (S3 URI)")
            self.assertTrue(
                code_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"CodeUri should be an S3 URI starting with s3://{self.s3_bucket.name}/, got: {code_uri}",
            )

            # Requirement 13.1: Verify the artifact was uploaded (check stderr for upload message)
            # Since all functions share the same static CodeUri, there should be only one upload
            uploads = re.findall(r"Uploading to.+", process_stderr)
            self.assertGreaterEqual(
                len(uploads),
                1,
                "At least one artifact should be uploaded",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_generates_mappings_for_dynamic_codeuri(self):
        """
        Test that sam package generates Mappings section for dynamic CodeUri.

        This test verifies:
        1. Package succeeds with dynamic CodeUri template
        2. Packaged template contains generated Mappings section (e.g., SAMCodeUriFunctions)
        3. CodeUri is replaced with Fn::FindInMap referencing the Mappings
        4. Fn::ForEach structure is preserved
        5. Each artifact has a unique content-based S3 key

        Validates Requirements: 4.2, 4.3, 4.4, 4.5, 4.6
        """
        template_path = self.test_data_path.joinpath("language-extensions-dynamic-codeuri", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            process_stdout = stdout.strip().decode("utf-8")
            process_stderr = stderr.strip().decode("utf-8")

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stdout: {process_stdout}, stderr: {process_stderr}",
            )

            # Read the packaged template using SAM CLI's YAML parser
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Requirement 4.3, 4.6: Verify Mappings section is generated with correct naming
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMCodeUriFunctions"  # SAM{PropertyName}{LoopName}

            self.assertIn(
                mapping_name,
                mappings,
                f"Packaged template should contain generated Mappings section '{mapping_name}'",
            )

            # Verify Mappings contains entries for each collection value
            mapping_entries = mappings[mapping_name]
            self.assertIn("Alpha", mapping_entries, "Mappings should contain entry for 'Alpha'")
            self.assertIn("Beta", mapping_entries, "Mappings should contain entry for 'Beta'")

            # Requirement 4.2: Verify each artifact has unique S3 key (content-based hash)
            alpha_uri = mapping_entries["Alpha"].get("CodeUri")
            beta_uri = mapping_entries["Beta"].get("CodeUri")

            self.assertIsNotNone(alpha_uri, "Alpha CodeUri should be present in Mappings")
            self.assertIsNotNone(beta_uri, "Beta CodeUri should be present in Mappings")
            self.assertTrue(
                alpha_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Alpha CodeUri should be an S3 URI, got: {alpha_uri}",
            )
            self.assertTrue(
                beta_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Beta CodeUri should be an S3 URI, got: {beta_uri}",
            )

            # Verify unique S3 keys (different content should have different hashes)
            # Note: Alpha and Beta have different content, so they should have different S3 keys
            self.assertNotEqual(
                alpha_uri,
                beta_uri,
                "Alpha and Beta should have different S3 URIs (unique content-based hashes)",
            )

            # Requirement 4.5: Verify Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Functions"

            self.assertIn(
                foreach_key,
                resources,
                f"Packaged template should preserve {foreach_key} structure",
            )

            # Verify the Fn::ForEach structure is correct
            foreach_block = resources[foreach_key]
            self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
            self.assertEqual(
                len(foreach_block),
                3,
                "Fn::ForEach block should have 3 elements: variable, collection, body",
            )

            # Verify the loop variable and collection are preserved
            loop_variable = foreach_block[0]
            self.assertEqual(loop_variable, "FunctionName", "Loop variable should be 'FunctionName'")

            collection = foreach_block[1]
            self.assertEqual(collection, ["Alpha", "Beta"], "Collection should be preserved")

            # Requirement 4.4: Verify CodeUri is replaced with Fn::FindInMap
            body_template = foreach_block[2]
            function_template = body_template.get("${FunctionName}Function", {})
            properties = function_template.get("Properties", {})
            code_uri = properties.get("CodeUri")

            self.assertIsInstance(
                code_uri,
                dict,
                "CodeUri should be a dict (Fn::FindInMap reference)",
            )
            self.assertIn(
                "Fn::FindInMap",
                code_uri,
                "CodeUri should contain Fn::FindInMap",
            )

            # Verify Fn::FindInMap structure
            find_in_map = code_uri["Fn::FindInMap"]
            self.assertIsInstance(find_in_map, list, "Fn::FindInMap should be a list")
            self.assertEqual(len(find_in_map), 3, "Fn::FindInMap should have 3 elements")
            self.assertEqual(
                find_in_map[0],
                mapping_name,
                f"Fn::FindInMap should reference {mapping_name}",
            )
            self.assertEqual(
                find_in_map[1],
                {"Ref": "FunctionName"},
                "Fn::FindInMap should use loop variable as key",
            )
            self.assertEqual(
                find_in_map[2],
                "CodeUri",
                "Fn::FindInMap should look up 'CodeUri' property",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_dynamic_codeuri_unique_s3_keys(self):
        """
        Test that each artifact in dynamic CodeUri has a unique content-based S3 key.

        This test verifies:
        1. Package succeeds with dynamic CodeUri template
        2. Each collection value maps to a unique S3 URI
        3. S3 URIs contain content-based hashes

        Validates Requirements: 4.2
        """
        template_path = self.test_data_path.joinpath("language-extensions-dynamic-codeuri", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stderr: {stderr.decode('utf-8')}",
            )

            # Read the packaged template
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Get the Mappings section
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMCodeUriFunctions"
            mapping_entries = mappings.get(mapping_name, {})

            # Collect all S3 URIs
            s3_uris = []
            for collection_value in ["Alpha", "Beta"]:
                entry = mapping_entries.get(collection_value, {})
                code_uri = entry.get("CodeUri")
                self.assertIsNotNone(
                    code_uri,
                    f"CodeUri should be present for {collection_value}",
                )
                s3_uris.append(code_uri)

            # Verify all S3 URIs are unique (content-based hashing)
            self.assertEqual(
                len(s3_uris),
                len(set(s3_uris)),
                "All S3 URIs should be unique (content-based hashing)",
            )

            # Verify S3 URIs contain hash-like patterns (content-based)
            for uri in s3_uris:
                # S3 URI format: s3://bucket/prefix/hash.zip or s3://bucket/prefix/hash
                self.assertTrue(
                    uri.startswith("s3://"),
                    f"S3 URI should start with s3://, got: {uri}",
                )
                # Extract the key part (after bucket name)
                key_part = uri.split("/")[-1]
                # Content-based hash should be a hex string (at least 8 chars)
                self.assertGreaterEqual(
                    len(key_part.replace(".zip", "")),
                    8,
                    f"S3 key should contain content-based hash, got: {key_part}",
                )

            # Clean up
            os.unlink(output_template.name)

    def test_package_dynamic_codeuri_with_json_output(self):
        """
        Test that sam package with --use-json preserves Mappings and Fn::FindInMap for dynamic CodeUri.

        This test verifies:
        1. Package succeeds with --use-json flag
        2. JSON output contains generated Mappings section
        3. JSON output preserves Fn::ForEach structure with Fn::FindInMap

        Validates Requirements: 4.3, 4.4, 4.5
        """
        template_path = self.test_data_path.joinpath("language-extensions-dynamic-codeuri", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
                use_json=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stderr: {stderr.decode('utf-8')}",
            )

            # Read the packaged template as JSON
            with open(output_template.name, "r") as f:
                packaged_template = json.load(f)

            # Verify Mappings section is present in JSON output
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMCodeUriFunctions"

            self.assertIn(
                mapping_name,
                mappings,
                f"JSON packaged template should contain {mapping_name} Mappings",
            )

            # Verify Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Functions"

            self.assertIn(
                foreach_key,
                resources,
                f"JSON packaged template should preserve {foreach_key} structure",
            )

            # Verify CodeUri is Fn::FindInMap in JSON output
            foreach_block = resources[foreach_key]
            body_template = foreach_block[2]
            function_template = body_template.get("${FunctionName}Function", {})
            properties = function_template.get("Properties", {})
            code_uri = properties.get("CodeUri")

            self.assertIsInstance(
                code_uri,
                dict,
                "CodeUri should be a dict in JSON output",
            )
            self.assertIn(
                "Fn::FindInMap",
                code_uri,
                "CodeUri should contain Fn::FindInMap in JSON output",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_foreach_same_s3_uri_for_all_functions(self):
        """
        Test that sam package uses the same S3 URI for all functions with static CodeUri.

        This test verifies:
        1. Package succeeds with language extensions template
        2. The S3 URI in the packaged template is the same for all functions
        3. The Fn::ForEach structure is preserved with the shared S3 URI

        Validates Requirements: 13.1, 13.3
        """
        template_path = self.test_data_path.joinpath("language-extensions-foreach", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stderr: {stderr.decode('utf-8')}",
            )

            # Read the packaged template using SAM CLI's YAML parser
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Get the Fn::ForEach block
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Functions"
            foreach_block = resources.get(foreach_key)

            self.assertIsNotNone(foreach_block, f"{foreach_key} should exist in packaged template")

            # Get the function template from the body
            body_template = foreach_block[2]
            function_template = body_template.get("${FunctionName}Function", {})
            properties = function_template.get("Properties", {})
            code_uri = properties.get("CodeUri")

            # Requirement 13.3: The S3 URI should be the same for all functions
            # Since the Fn::ForEach structure is preserved with a single CodeUri value,
            # all expanded functions will use the same S3 URI
            self.assertIsNotNone(code_uri, "CodeUri should be present")
            self.assertTrue(
                code_uri.startswith("s3://"),
                f"CodeUri should be an S3 URI, got: {code_uri}",
            )

            # Verify the S3 URI contains the bucket name and a hash
            self.assertIn(
                self.s3_bucket.name,
                code_uri,
                f"S3 URI should contain bucket name {self.s3_bucket.name}",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_foreach_with_json_output(self):
        """
        Test that sam package with --use-json preserves Fn::ForEach structure.

        This test verifies:
        1. Package succeeds with --use-json flag
        2. JSON output preserves Fn::ForEach structure
        3. S3 URI is correctly set in JSON output

        Validates Requirements: 13.2, 13.3
        """
        template_path = self.test_data_path.joinpath("language-extensions-foreach", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
                use_json=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stderr: {stderr.decode('utf-8')}",
            )

            # Read the packaged template as JSON
            with open(output_template.name, "r") as f:
                packaged_template = json.load(f)

            # Verify Fn::ForEach structure is preserved in JSON output
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Functions"

            self.assertIn(
                foreach_key,
                resources,
                f"JSON packaged template should preserve {foreach_key} structure",
            )

            # Verify the structure
            foreach_block = resources[foreach_key]
            self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
            self.assertEqual(len(foreach_block), 3, "Fn::ForEach block should have 3 elements")

            # Verify CodeUri is S3 URI
            body_template = foreach_block[2]
            function_template = body_template.get("${FunctionName}Function", {})
            properties = function_template.get("Properties", {})
            code_uri = properties.get("CodeUri")

            self.assertTrue(
                code_uri.startswith("s3://"),
                f"CodeUri should be an S3 URI in JSON output, got: {code_uri}",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_emits_warning_for_param_based_collection_with_dynamic_codeuri(self):
        """
        Test that sam package emits warning for parameter-based collection with dynamic CodeUri.

        This test verifies:
        1. Package succeeds with parameter-based collection and dynamic CodeUri
        2. A warning is emitted about collection values being fixed at package time
        3. Packaged template contains generated Mappings section
        4. Fn::ForEach structure is preserved

        Validates Requirements: 4.8
        """
        template_path = self.test_data_path.joinpath("language-extensions-param-dynamic-codeuri", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            process_stdout = stdout.strip().decode("utf-8")
            process_stderr = stderr.strip().decode("utf-8")

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stdout: {process_stdout}, stderr: {process_stderr}",
            )

            # Requirement 4.8: Verify warning is emitted about collection values being fixed at package time
            # The warning should mention:
            # - The Fn::ForEach loop name (Services)
            # - Dynamic CodeUri
            # - Parameter-based collection
            # - Need to re-package if parameter changes
            combined_output = process_stdout + process_stderr

            # Check for warning about parameter-based collection with dynamic CodeUri
            warning_patterns = [
                r"[Ww]arning",  # Should contain "Warning" or "warning"
                r"Services",  # Should mention the ForEach loop name
                r"(parameter|re-?package|fixed|package time)",  # Should mention parameter or re-package
            ]

            warning_found = False
            for pattern in warning_patterns:
                if re.search(pattern, combined_output, re.IGNORECASE):
                    warning_found = True
                    break

            self.assertTrue(
                warning_found,
                f"Expected warning about parameter-based collection with dynamic CodeUri. "
                f"Output was:\nstdout: {process_stdout}\nstderr: {process_stderr}",
            )

            # Verify success message is still present
            self.assertIn(
                f"Successfully packaged artifacts and wrote output template to file {output_template.name}",
                process_stdout,
            )

            # Read the packaged template using SAM CLI's YAML parser
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Verify Mappings section is generated with correct naming
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMCodeUriServices"  # SAM{PropertyName}{LoopName}

            self.assertIn(
                mapping_name,
                mappings,
                f"Packaged template should contain generated Mappings section '{mapping_name}'",
            )

            # Verify Mappings contains entries for each default collection value
            mapping_entries = mappings[mapping_name]
            self.assertIn("Users", mapping_entries, "Mappings should contain entry for 'Users'")
            self.assertIn("Orders", mapping_entries, "Mappings should contain entry for 'Orders'")

            # Verify each artifact has S3 URI
            users_uri = mapping_entries["Users"].get("CodeUri")
            orders_uri = mapping_entries["Orders"].get("CodeUri")

            self.assertIsNotNone(users_uri, "Users CodeUri should be present in Mappings")
            self.assertIsNotNone(orders_uri, "Orders CodeUri should be present in Mappings")
            self.assertTrue(
                users_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Users CodeUri should be an S3 URI, got: {users_uri}",
            )
            self.assertTrue(
                orders_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Orders CodeUri should be an S3 URI, got: {orders_uri}",
            )

            # Verify Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Services"

            self.assertIn(
                foreach_key,
                resources,
                f"Packaged template should preserve {foreach_key} structure",
            )

            # Verify the Fn::ForEach structure is correct
            foreach_block = resources[foreach_key]
            self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
            self.assertEqual(
                len(foreach_block),
                3,
                "Fn::ForEach block should have 3 elements: variable, collection, body",
            )

            # Verify the loop variable
            loop_variable = foreach_block[0]
            self.assertEqual(loop_variable, "Name", "Loop variable should be 'Name'")

            # Verify CodeUri is replaced with Fn::FindInMap
            body_template = foreach_block[2]
            function_template = body_template.get("${Name}Service", {})
            properties = function_template.get("Properties", {})
            code_uri = properties.get("CodeUri")

            self.assertIsInstance(
                code_uri,
                dict,
                "CodeUri should be a dict (Fn::FindInMap reference)",
            )
            self.assertIn(
                "Fn::FindInMap",
                code_uri,
                "CodeUri should contain Fn::FindInMap",
            )

            # Verify Fn::FindInMap structure
            find_in_map = code_uri["Fn::FindInMap"]
            self.assertIsInstance(find_in_map, list, "Fn::FindInMap should be a list")
            self.assertEqual(len(find_in_map), 3, "Fn::FindInMap should have 3 elements")
            self.assertEqual(
                find_in_map[0],
                mapping_name,
                f"Fn::FindInMap should reference {mapping_name}",
            )
            self.assertEqual(
                find_in_map[1],
                {"Ref": "Name"},
                "Fn::FindInMap should use loop variable as key",
            )
            self.assertEqual(
                find_in_map[2],
                "CodeUri",
                "Fn::FindInMap should look up 'CodeUri' property",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_fails_for_invalid_mapping_key_characters(self):
        """
        Test that sam package fails with clear error for invalid Mapping key characters.

        This test verifies:
        1. Package fails when collection values contain invalid characters for CloudFormation Mapping keys
        2. Error message clearly indicates which values are invalid
        3. Error message explains valid characters (alphanumeric, hyphens, underscores)

        CloudFormation Mapping keys can only contain alphanumeric characters (a-z, A-Z, 0-9),
        hyphens (-), and underscores (_). Characters like dots (.), slashes (/), and spaces
        are not allowed.

        Validates Requirements: 4.10
        """
        template_path = self.test_data_path.joinpath("language-extensions-invalid-mapping-keys", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            process_stdout = stdout.strip().decode("utf-8")
            process_stderr = stderr.strip().decode("utf-8")
            combined_output = process_stdout + process_stderr

            # Verify package fails (non-zero exit code)
            self.assertNotEqual(
                process.returncode,
                0,
                f"Package should fail for invalid Mapping key characters. "
                f"stdout: {process_stdout}, stderr: {process_stderr}",
            )

            # Verify error message mentions invalid Mapping key characters
            # The error should mention:
            # - "Invalid" or "invalid"
            # - "Mapping" or "mapping"
            # - The invalid value "order.service"
            # - Valid characters (alphanumeric, hyphens, underscores)
            self.assertTrue(
                "invalid" in combined_output.lower() or "Invalid" in combined_output,
                f"Error message should mention 'invalid'. Output: {combined_output}",
            )

            self.assertTrue(
                "order.service" in combined_output,
                f"Error message should mention the invalid value 'order.service'. Output: {combined_output}",
            )

            # Verify error message explains valid characters
            # Should mention alphanumeric, hyphens, or underscores
            valid_chars_mentioned = any(
                term in combined_output.lower()
                for term in ["alphanumeric", "hyphen", "underscore", "a-z", "0-9", "_", "-"]
            )
            self.assertTrue(
                valid_chars_mentioned,
                f"Error message should explain valid characters. Output: {combined_output}",
            )

            # Clean up
            try:
                os.unlink(output_template.name)
            except FileNotFoundError:
                pass  # File may not have been created if package failed early


@skipIf(SKIP_PACKAGE_TESTS, "Skip package tests in CI/CD only")
class TestPackageLanguageExtensionsArtifactFormats(PackageIntegBase):
    """
    Integration tests for sam package with all artifact property formats in Fn::ForEach.

    Tests that sam package correctly generates Mappings for:
    - AWS::Serverless::LayerVersion with dynamic ContentUri
    - AWS::Serverless::Api with dynamic DefinitionUri
    - AWS::Serverless::StateMachine with dynamic DefinitionUri

    Validates Requirements: 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.test_data_path = Path(__file__).resolve().parents[1].joinpath("testdata", "package")

    def test_package_generates_mappings_for_dynamic_contenturi_layer(self):
        """
        Test that sam package generates Mappings for LayerVersion with dynamic ContentUri.

        This test verifies:
        1. Package succeeds with dynamic ContentUri template
        2. Packaged template contains generated Mappings section (e.g., SAMContentUriLayers)
        3. ContentUri is replaced with Fn::FindInMap referencing the Mappings
        4. Fn::ForEach structure is preserved
        5. Each layer artifact has a unique content-based S3 key

        Validates Requirements: 20.1, 20.5, 20.6, 20.7
        """
        template_path = self.test_data_path.joinpath("language-extensions-dynamic-contenturi", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            process_stdout = stdout.strip().decode("utf-8")
            process_stderr = stderr.strip().decode("utf-8")

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stdout: {process_stdout}, stderr: {process_stderr}",
            )

            # Read the packaged template
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Requirement 20.5: Verify Mappings section is generated with correct naming
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMContentUriLayers"  # SAM{PropertyName}{LoopName}

            self.assertIn(
                mapping_name,
                mappings,
                f"Packaged template should contain generated Mappings section '{mapping_name}'",
            )

            # Verify Mappings contains entries for each collection value
            mapping_entries = mappings[mapping_name]
            self.assertIn("Common", mapping_entries, "Mappings should contain entry for 'Common'")
            self.assertIn("Utils", mapping_entries, "Mappings should contain entry for 'Utils'")

            # Verify each layer has unique S3 key (content-based hash)
            common_uri = mapping_entries["Common"].get("ContentUri")
            utils_uri = mapping_entries["Utils"].get("ContentUri")

            self.assertIsNotNone(common_uri, "Common ContentUri should be present in Mappings")
            self.assertIsNotNone(utils_uri, "Utils ContentUri should be present in Mappings")
            self.assertTrue(
                common_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Common ContentUri should be an S3 URI, got: {common_uri}",
            )
            self.assertTrue(
                utils_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Utils ContentUri should be an S3 URI, got: {utils_uri}",
            )

            # Verify unique S3 keys (different content should have different hashes)
            self.assertNotEqual(
                common_uri,
                utils_uri,
                "Common and Utils should have different S3 URIs (unique content-based hashes)",
            )

            # Requirement 20.7: Verify Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Layers"

            self.assertIn(
                foreach_key,
                resources,
                f"Packaged template should preserve {foreach_key} structure",
            )

            # Verify the Fn::ForEach structure is correct
            foreach_block = resources[foreach_key]
            self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
            self.assertEqual(
                len(foreach_block),
                3,
                "Fn::ForEach block should have 3 elements: variable, collection, body",
            )

            # Verify the loop variable and collection are preserved
            loop_variable = foreach_block[0]
            self.assertEqual(loop_variable, "LayerName", "Loop variable should be 'LayerName'")

            collection = foreach_block[1]
            self.assertEqual(collection, ["Common", "Utils"], "Collection should be preserved")

            # Requirement 20.6: Verify ContentUri is replaced with Fn::FindInMap
            body_template = foreach_block[2]
            layer_template = body_template.get("${LayerName}Layer", {})
            properties = layer_template.get("Properties", {})
            content_uri = properties.get("ContentUri")

            self.assertIsInstance(
                content_uri,
                dict,
                "ContentUri should be a dict (Fn::FindInMap reference)",
            )
            self.assertIn(
                "Fn::FindInMap",
                content_uri,
                "ContentUri should contain Fn::FindInMap",
            )

            # Verify Fn::FindInMap structure
            find_in_map = content_uri["Fn::FindInMap"]
            self.assertIsInstance(find_in_map, list, "Fn::FindInMap should be a list")
            self.assertEqual(len(find_in_map), 3, "Fn::FindInMap should have 3 elements")
            self.assertEqual(
                find_in_map[0],
                mapping_name,
                f"Fn::FindInMap should reference {mapping_name}",
            )
            self.assertEqual(
                find_in_map[1],
                {"Ref": "LayerName"},
                "Fn::FindInMap should use loop variable as key",
            )
            self.assertEqual(
                find_in_map[2],
                "ContentUri",
                "Fn::FindInMap should look up 'ContentUri' property",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_generates_mappings_for_dynamic_definitionuri_api(self):
        """
        Test that sam package generates Mappings for Api with dynamic DefinitionUri.

        This test verifies:
        1. Package succeeds with dynamic DefinitionUri template for APIs
        2. Packaged template contains generated Mappings section (e.g., SAMDefinitionUriAPIs)
        3. DefinitionUri is replaced with Fn::FindInMap referencing the Mappings
        4. Fn::ForEach structure is preserved
        5. Each API spec has a unique content-based S3 key

        Validates Requirements: 20.2, 20.5, 20.6, 20.7
        """
        template_path = self.test_data_path.joinpath("language-extensions-dynamic-definitionuri-api", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            process_stdout = stdout.strip().decode("utf-8")
            process_stderr = stderr.strip().decode("utf-8")

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stdout: {process_stdout}, stderr: {process_stderr}",
            )

            # Read the packaged template
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Requirement 20.5: Verify Mappings section is generated with correct naming
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMDefinitionUriAPIs"  # SAM{PropertyName}{LoopName}

            self.assertIn(
                mapping_name,
                mappings,
                f"Packaged template should contain generated Mappings section '{mapping_name}'",
            )

            # Verify Mappings contains entries for each collection value
            mapping_entries = mappings[mapping_name]
            self.assertIn("Users", mapping_entries, "Mappings should contain entry for 'Users'")
            self.assertIn("Orders", mapping_entries, "Mappings should contain entry for 'Orders'")

            # Verify each API spec has unique S3 key (content-based hash)
            users_uri = mapping_entries["Users"].get("DefinitionUri")
            orders_uri = mapping_entries["Orders"].get("DefinitionUri")

            self.assertIsNotNone(users_uri, "Users DefinitionUri should be present in Mappings")
            self.assertIsNotNone(orders_uri, "Orders DefinitionUri should be present in Mappings")
            self.assertTrue(
                users_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Users DefinitionUri should be an S3 URI, got: {users_uri}",
            )
            self.assertTrue(
                orders_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Orders DefinitionUri should be an S3 URI, got: {orders_uri}",
            )

            # Verify unique S3 keys (different content should have different hashes)
            self.assertNotEqual(
                users_uri,
                orders_uri,
                "Users and Orders should have different S3 URIs (unique content-based hashes)",
            )

            # Requirement 20.7: Verify Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::APIs"

            self.assertIn(
                foreach_key,
                resources,
                f"Packaged template should preserve {foreach_key} structure",
            )

            # Verify the Fn::ForEach structure is correct
            foreach_block = resources[foreach_key]
            self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
            self.assertEqual(
                len(foreach_block),
                3,
                "Fn::ForEach block should have 3 elements: variable, collection, body",
            )

            # Verify the loop variable and collection are preserved
            loop_variable = foreach_block[0]
            self.assertEqual(loop_variable, "ApiName", "Loop variable should be 'ApiName'")

            collection = foreach_block[1]
            self.assertEqual(collection, ["Users", "Orders"], "Collection should be preserved")

            # Requirement 20.6: Verify DefinitionUri is replaced with Fn::FindInMap
            body_template = foreach_block[2]
            api_template = body_template.get("${ApiName}Api", {})
            properties = api_template.get("Properties", {})
            definition_uri = properties.get("DefinitionUri")

            self.assertIsInstance(
                definition_uri,
                dict,
                "DefinitionUri should be a dict (Fn::FindInMap reference)",
            )
            self.assertIn(
                "Fn::FindInMap",
                definition_uri,
                "DefinitionUri should contain Fn::FindInMap",
            )

            # Verify Fn::FindInMap structure
            find_in_map = definition_uri["Fn::FindInMap"]
            self.assertIsInstance(find_in_map, list, "Fn::FindInMap should be a list")
            self.assertEqual(len(find_in_map), 3, "Fn::FindInMap should have 3 elements")
            self.assertEqual(
                find_in_map[0],
                mapping_name,
                f"Fn::FindInMap should reference {mapping_name}",
            )
            self.assertEqual(
                find_in_map[1],
                {"Ref": "ApiName"},
                "Fn::FindInMap should use loop variable as key",
            )
            self.assertEqual(
                find_in_map[2],
                "DefinitionUri",
                "Fn::FindInMap should look up 'DefinitionUri' property",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_generates_mappings_for_dynamic_definitionuri_statemachine(self):
        """
        Test that sam package generates Mappings for StateMachine with dynamic DefinitionUri.

        This test verifies:
        1. Package succeeds with dynamic DefinitionUri template for State Machines
        2. Packaged template contains generated Mappings section (e.g., SAMDefinitionUriWorkflows)
        3. DefinitionUri is replaced with Fn::FindInMap referencing the Mappings
        4. Fn::ForEach structure is preserved
        5. Each state machine definition has a unique content-based S3 key

        Validates Requirements: 20.3, 20.5, 20.6, 20.7
        """
        template_path = self.test_data_path.joinpath(
            "language-extensions-dynamic-definitionuri-statemachine", "template.yaml"
        )

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template=template_path,
                s3_prefix=self.s3_prefix,
                output_template_file=output_template.name,
                force_upload=True,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            process_stdout = stdout.strip().decode("utf-8")
            process_stderr = stderr.strip().decode("utf-8")

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stdout: {process_stdout}, stderr: {process_stderr}",
            )

            # Read the packaged template
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Requirement 20.5: Verify Mappings section is generated with correct naming
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMDefinitionUriWorkflows"  # SAM{PropertyName}{LoopName}

            self.assertIn(
                mapping_name,
                mappings,
                f"Packaged template should contain generated Mappings section '{mapping_name}'",
            )

            # Verify Mappings contains entries for each collection value
            mapping_entries = mappings[mapping_name]
            self.assertIn("Process", mapping_entries, "Mappings should contain entry for 'Process'")
            self.assertIn("Notify", mapping_entries, "Mappings should contain entry for 'Notify'")

            # Verify each state machine definition has unique S3 key (content-based hash)
            process_uri = mapping_entries["Process"].get("DefinitionUri")
            notify_uri = mapping_entries["Notify"].get("DefinitionUri")

            self.assertIsNotNone(process_uri, "Process DefinitionUri should be present in Mappings")
            self.assertIsNotNone(notify_uri, "Notify DefinitionUri should be present in Mappings")
            self.assertTrue(
                process_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Process DefinitionUri should be an S3 URI, got: {process_uri}",
            )
            self.assertTrue(
                notify_uri.startswith(f"s3://{self.s3_bucket.name}/"),
                f"Notify DefinitionUri should be an S3 URI, got: {notify_uri}",
            )

            # Verify unique S3 keys (different content should have different hashes)
            self.assertNotEqual(
                process_uri,
                notify_uri,
                "Process and Notify should have different S3 URIs (unique content-based hashes)",
            )

            # Requirement 20.7: Verify Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Workflows"

            self.assertIn(
                foreach_key,
                resources,
                f"Packaged template should preserve {foreach_key} structure",
            )

            # Verify the Fn::ForEach structure is correct
            foreach_block = resources[foreach_key]
            self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
            self.assertEqual(
                len(foreach_block),
                3,
                "Fn::ForEach block should have 3 elements: variable, collection, body",
            )

            # Verify the loop variable and collection are preserved
            loop_variable = foreach_block[0]
            self.assertEqual(loop_variable, "WorkflowName", "Loop variable should be 'WorkflowName'")

            collection = foreach_block[1]
            self.assertEqual(collection, ["Process", "Notify"], "Collection should be preserved")

            # Requirement 20.6: Verify DefinitionUri is replaced with Fn::FindInMap
            body_template = foreach_block[2]
            workflow_template = body_template.get("${WorkflowName}Workflow", {})
            properties = workflow_template.get("Properties", {})
            definition_uri = properties.get("DefinitionUri")

            self.assertIsInstance(
                definition_uri,
                dict,
                "DefinitionUri should be a dict (Fn::FindInMap reference)",
            )
            self.assertIn(
                "Fn::FindInMap",
                definition_uri,
                "DefinitionUri should contain Fn::FindInMap",
            )

            # Verify Fn::FindInMap structure
            find_in_map = definition_uri["Fn::FindInMap"]
            self.assertIsInstance(find_in_map, list, "Fn::FindInMap should be a list")
            self.assertEqual(len(find_in_map), 3, "Fn::FindInMap should have 3 elements")
            self.assertEqual(
                find_in_map[0],
                mapping_name,
                f"Fn::FindInMap should reference {mapping_name}",
            )
            self.assertEqual(
                find_in_map[1],
                {"Ref": "WorkflowName"},
                "Fn::FindInMap should use loop variable as key",
            )
            self.assertEqual(
                find_in_map[2],
                "DefinitionUri",
                "Fn::FindInMap should look up 'DefinitionUri' property",
            )

            # Clean up
            os.unlink(output_template.name)


@skipIf(SKIP_PACKAGE_TESTS, "Skip package tests in CI/CD only")
class TestPackageLanguageExtensionsImageUri(PackageIntegBase):
    """
    Integration tests for sam package with Fn::ForEach and dynamic ImageUri.

    Tests that sam package correctly generates Mappings for:
    - AWS::Serverless::Function with dynamic ImageUri (container images)

    Validates Requirements: 19.2, 20.5, 20.6, 20.7
    """

    @classmethod
    def setUpClass(cls):
        from samcli.local.docker.utils import get_validated_container_client

        cls.docker_client = get_validated_container_client()
        cls.local_images = [
            ("public.ecr.aws/sam/emulation-python3.9", "latest"),
        ]
        # Setup local images by pulling and tagging them for the test
        # Docker repository names must be lowercase
        for repo, tag in cls.local_images:
            cls.docker_client.api.pull(repository=repo, tag=tag)
            # Tag for alpha and beta functions
            cls.docker_client.api.tag(f"{repo}:{tag}", "emulation-python3.9-alpha", tag="latest")
            cls.docker_client.api.tag(f"{repo}:{tag}", "emulation-python3.9-beta", tag="latest")

        super().setUpClass()
        cls.test_data_path = Path(__file__).resolve().parents[1].joinpath("testdata", "package")

    def test_package_generates_mappings_for_dynamic_imageuri(self):
        """
        Test that sam package generates Mappings for Function with dynamic ImageUri.

        This test verifies:
        1. Package succeeds with dynamic ImageUri template
        2. Packaged template contains generated Mappings section (e.g., SAMImageUriFunctions)
        3. ImageUri is replaced with Fn::FindInMap referencing the Mappings
        4. Fn::ForEach structure is preserved
        5. Each container image has a unique ECR URI

        Validates Requirements: 19.2, 20.5, 20.6, 20.7
        """
        template_path = self.test_data_path.joinpath("language-extensions-dynamic-imageuri", "template.yaml")

        with tempfile.NamedTemporaryFile(delete=False, suffix=".yaml") as output_template:
            command_list = PackageIntegBase.get_command_list(
                image_repository=self.ecr_repo_name,
                template=template_path,
                output_template_file=output_template.name,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            process_stdout = stdout.strip().decode("utf-8")
            process_stderr = stderr.strip().decode("utf-8")

            # Verify package succeeds
            self.assertEqual(
                process.returncode,
                0,
                f"Package failed with stdout: {process_stdout}, stderr: {process_stderr}",
            )

            # Read the packaged template
            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Requirement 20.5: Verify Mappings section is generated with correct naming
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMImageUriFunctions"  # SAM{PropertyName}{LoopName}

            self.assertIn(
                mapping_name,
                mappings,
                f"Packaged template should contain generated Mappings section '{mapping_name}'",
            )

            # Verify Mappings contains entries for each collection value
            mapping_entries = mappings[mapping_name]
            self.assertIn("alpha", mapping_entries, "Mappings should contain entry for 'alpha'")
            self.assertIn("beta", mapping_entries, "Mappings should contain entry for 'beta'")

            # Verify each function has unique ECR URI
            alpha_uri = mapping_entries["alpha"].get("ImageUri")
            beta_uri = mapping_entries["beta"].get("ImageUri")

            self.assertIsNotNone(alpha_uri, "alpha ImageUri should be present in Mappings")
            self.assertIsNotNone(beta_uri, "beta ImageUri should be present in Mappings")

            # ECR URIs should contain the ECR repo name
            self.assertIn(
                self.ecr_repo_name.split("/")[-1],  # Get repo name without account prefix
                alpha_uri,
                f"Alpha ImageUri should contain ECR repo, got: {alpha_uri}",
            )
            self.assertIn(
                self.ecr_repo_name.split("/")[-1],
                beta_uri,
                f"Beta ImageUri should contain ECR repo, got: {beta_uri}",
            )

            # Verify unique ECR URIs (different images should have different digests)
            self.assertNotEqual(
                alpha_uri,
                beta_uri,
                "Alpha and Beta should have different ECR URIs (unique image digests)",
            )

            # Requirement 20.7: Verify Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            foreach_key = "Fn::ForEach::Functions"

            self.assertIn(
                foreach_key,
                resources,
                f"Packaged template should preserve {foreach_key} structure",
            )

            # Verify the Fn::ForEach structure is correct
            foreach_block = resources[foreach_key]
            self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
            self.assertEqual(
                len(foreach_block),
                3,
                "Fn::ForEach block should have 3 elements: variable, collection, body",
            )

            # Verify the loop variable and collection are preserved
            loop_variable = foreach_block[0]
            self.assertEqual(loop_variable, "FunctionName", "Loop variable should be 'FunctionName'")

            collection = foreach_block[1]
            self.assertEqual(collection, ["alpha", "beta"], "Collection should be preserved")

            # Requirement 20.6: Verify ImageUri is replaced with Fn::FindInMap
            body_template = foreach_block[2]
            function_template = body_template.get("${FunctionName}Function", {})
            properties = function_template.get("Properties", {})
            image_uri = properties.get("ImageUri")

            self.assertIsInstance(
                image_uri,
                dict,
                "ImageUri should be a dict (Fn::FindInMap reference)",
            )
            self.assertIn(
                "Fn::FindInMap",
                image_uri,
                "ImageUri should contain Fn::FindInMap",
            )

            # Verify Fn::FindInMap structure
            find_in_map = image_uri["Fn::FindInMap"]
            self.assertIsInstance(find_in_map, list, "Fn::FindInMap should be a list")
            self.assertEqual(len(find_in_map), 3, "Fn::FindInMap should have 3 elements")
            self.assertEqual(
                find_in_map[0],
                mapping_name,
                f"Fn::FindInMap should reference {mapping_name}",
            )
            self.assertEqual(
                find_in_map[1],
                {"Ref": "FunctionName"},
                "Fn::FindInMap should use loop variable as key",
            )
            self.assertEqual(
                find_in_map[2],
                "ImageUri",
                "Fn::FindInMap should look up 'ImageUri' property",
            )

            # Clean up
            os.unlink(output_template.name)

    def test_package_nested_foreach_dynamic_codeuri_generates_mappings(self):
        """
        Test that sam package with nested Fn::ForEach and dynamic CodeUri generates Mappings.

        Validates Requirements: 25.5, 25.9
        """
        template_path = self.test_data_path.joinpath(
            "language-extensions-nested-foreach-dynamic-codeuri", "template.yaml"
        )

        output_template = tempfile.NamedTemporaryFile(delete=False, suffix=".yaml")
        try:
            command_list = self.get_command_list(
                s3_bucket=self.s3_bucket.name,
                template_file=str(template_path),
                output_template_file=output_template.name,
            )

            process = Popen(command_list, stdout=PIPE, stderr=PIPE)
            try:
                stdout, stderr = process.communicate(timeout=TIMEOUT)
            except TimeoutExpired:
                process.kill()
                raise

            self.assertEqual(
                process.returncode,
                0,
                f"Package failed: {stderr.decode('utf-8')}",
            )

            with open(output_template.name, "r") as f:
                packaged_template = yaml_parse(f.read())

            # Verify nested Fn::ForEach structure is preserved
            resources = packaged_template.get("Resources", {})
            outer_key = "Fn::ForEach::Environments"
            self.assertIn(outer_key, resources)

            outer_block = resources[outer_key]
            inner_block = outer_block[2]["Fn::ForEach::Services"]
            self.assertEqual(inner_block[0], "Service")
            self.assertEqual(inner_block[1], ["Users", "Orders"])

            # Verify Mappings section was generated
            mappings = packaged_template.get("Mappings", {})
            mapping_name = "SAMCodeUriEnvironmentsServices"
            self.assertIn(mapping_name, mappings)
            self.assertIn("Users", mappings[mapping_name])
            self.assertIn("Orders", mappings[mapping_name])

            # Verify S3 URIs in Mappings
            users_uri = mappings[mapping_name]["Users"]["CodeUri"]
            orders_uri = mappings[mapping_name]["Orders"]["CodeUri"]
            self.assertTrue(users_uri.startswith("s3://"), f"Users URI should be S3: {users_uri}")
            self.assertTrue(orders_uri.startswith("s3://"), f"Orders URI should be S3: {orders_uri}")

            # Verify CodeUri replaced with Fn::FindInMap
            inner_body = inner_block[2]
            props = inner_body["${Env}${Service}Function"]["Properties"]
            codeuri = props["CodeUri"]
            self.assertIsInstance(codeuri, dict)
            self.assertIn("Fn::FindInMap", codeuri)
            self.assertEqual(codeuri["Fn::FindInMap"][0], mapping_name)
        finally:
            os.unlink(output_template.name)
