# Build customization
project_name: sam
builds:
  - 
    binary: sam
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386

    hooks:
      post: ./distribution/npm/npm-release.sh
 
archive:
  format: tar.gz
  files:
    - LICENSE
    - NOTICE

# Publish to Github Releases 
release:
    github:
        owner: awslabs
        name: aws-sam-local
 
    # Don't auto-publish the release. Admin has to manually publish at right time
    # Setting to true will also prevent brew from being published
    draft: false
 
# homebrew release
#brew:
# 
#    # repository to push the tap to.
#    folder: Formula
#    github:
#        owner: awslabs
#        name: homebrew-tap
# 
#    homepage: "https://github.com/awslabs/aws-sam-local"
#    description: "Develop and test your serverless applications locally without uploading to AWS Lambda"
#    test: |
#        output = shell_output(bin/"sam --version")
#        assert_match "sam version #{version}", output
# 
#    install: |
#        bin.install "aws-sam-local"

fpm: 
  vendor: Amazon Web Services
  homepage: https://github.com/awslabs/aws-sam-local
  maintainer: aws-sam-cli@amazon.com
  description: AWS SAM Local is a CLI tool for developing, testing and deploying Serverless applications.
  license: Apache 2.0
  formats:
    - deb
    - rpm
