# Build customization
project_name: sam
builds:
  - 
    binary: sam
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
 
# Publish to Github Releases 
release:
    github:
        owner: awslabs
        name: aws-sam-cli
 
    # Don't auto-publish the release. Admin has to manually publish at right time
    # Setting to true will also prevent brew from being published
    draft: false
 
# homebrew release
#brew:
# 
#    # repository to push the tap to.
#    folder: formula
#    github:
#        owner: awslabs
#        name: aws-sam-cli
# 
#    homepage: "https://github.com/awslabs/aws-sam-cli"
#    description: "develop and test your serverless applications locally without uploading to aws lambda" 
#    test: |
#        output = shell_output(bin/"sam --version")
#        assert_match "sam version #{version}", output
# 
#    install: |
#        bin.install "aws-sam-cli"
