version: 0.2

phases:

  install: 
    commands:

      - export GOPATH="${CODEBUILD_SRC_DIR}"
      - mkdir -p "${GOPATH}/bin"
      - export PATH=$GOPATH/bin:$PATH 
      - mkdir -p "${GOPATH}/src/github.com/awslabs"
      - ln -s "${CODEBUILD_SRC_DIR}" "${GOPATH}/src/github.com/awslabs/aws-sam-cli"
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:

      # Display some debug info
      - echo "GOPATH is ${GOPATH}"

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - cd "${GOPATH}/src/github.com/awslabs/aws-sam-cli"
      - go test .

  build:
    commands:

      # Create output directories
      - mkdir -p "${CODEBUILD_SRC_DIR}/windows"
      - mkdir -p "${CODEBUILD_SRC_DIR}/linux"
      - mkdir -p "${CODEBUILD_SRC_DIR}/osx"  
      
      # Build AWS SAM CLI
      - cd "${GOPATH}/src/github.com/awslabs/aws-sam-cli"
      - GOOS=linux go build -o "${CODEBUILD_SRC_DIR}/linux/sam"
      - GOOS=darwin go build -o "${CODEBUILD_SRC_DIR}/osx/sam"
      - GOOS=windows go build -o "${CODEBUILD_SRC_DIR}/windows/sam.exe"

      # Create a VERSION file with details on the git hash etc
      - echo "Git commit ${CODEBUILD_RESOLVED_SOURCE_VERSION}" > "${CODEBUILD_SRC_DIR}/VERSION"
      - echo "Built by AWS CodeBuild $(date)" >> "${CODEBUILD_SRC_DIR}/VERSION"

  post_build:
    commands:
    
      # Release the binaries to the public S3 bucket
      - aws s3 "${CODEBUILD_SRC_DIR}/linux/sam" s3://aws-sam-cli/releases/${CODEBUILD_RESOLVED_SOURCE_VERSION}/linux/sam
      - aws s3 "${CODEBUILD_SRC_DIR}/osx/sam" s3://aws-sam-cli/releases/${CODEBUILD_RESOLVED_SOURCE_VERSION}/osx/sam
      - aws s3 "${CODEBUILD_SRC_DIR}/windows/sam.exe" s3://aws-sam-cli/releases/${CODEBUILD_RESOLVED_SOURCE_VERSION}/windows/sam.exe
      - aws s3 "${CODEBUILD_SRC_DIR}/VERSION" s3://aws-sam-cli/releases/${CODEBUILD_RESOLVED_SOURCE_VERSION}/VERSION

      # Repoint the latest/ directory to this build
      - aws s3 cp s3://aws-sam-cli/releases/${CODEBUILD_RESOLVED_SOURCE_VERSION}/linux/sam s3://aws-sam-cli/releases/latest/linux/sam
      - aws s3 cp s3://aws-sam-cli/releases/${CODEBUILD_RESOLVED_SOURCE_VERSION}/osx/sam s3://aws-sam-cli/releases/latest/osx/sam
      - aws s3 cp s3://aws-sam-cli/releases/${CODEBUILD_RESOLVED_SOURCE_VERSION}/windows/sam.exe s3://aws-sam-cli/releases/latest/windows/sam.exe
      - aws s3 cp s3://aws-sam-cli/releases/${CODEBUILD_RESOLVED_SOURCE_VERSION}/VERSION s3://aws-sam-cli/releases/latest/VERSION

artifacts:
  files:
    - VERSION
    - linux/sam
    - osx/sam 
    - windows/sam.exe 
