"""
Integration tests for sam build with CloudFormation Language Extensions.

These tests verify that sam build correctly processes templates using
AWS::LanguageExtensions transform, including Fn::ForEach, Fn::ToJsonString,
Fn::Length intrinsic functions, and conditional DeletionPolicy/UpdateReplacePolicy.

Requirements tested:
- 3.1: sam build expands Fn::ForEach and builds each generated function
- 3.3: sam build creates build artifacts for all expanded functions in .aws-sam/build/
- 12.1: Integration tests verify sam build successfully builds functions generated by Fn::ForEach
"""

import logging
import os
import sys
from pathlib import Path

import pytest
import yaml

from tests.integration.buildcmd.build_integ_base import BuildIntegBase
from tests.testing_utils import run_command

LOG = logging.getLogger(__name__)


@pytest.mark.python
class TestBuildCommand_LanguageExtensions(BuildIntegBase):
    """
    Integration tests for sam build with CloudFormation Language Extensions.

    Tests that sam build correctly processes templates with:
    - Fn::ForEach generating multiple Lambda functions
    - Fn::ToJsonString in environment variables
    - Fn::Length for array operations
    - Conditional DeletionPolicy and UpdateReplacePolicy using Fn::If

    Validates Requirements: 3.1, 3.3, 12.1
    """

    template = "language-extensions.yaml"

    # Expected files in the build artifact for Python functions
    EXPECTED_FILES_PROJECT_MANIFEST = {
        "__init__.py",
        "main.py",
    }

    # Functions generated by Fn::ForEach
    FOREACH_GENERATED_FUNCTIONS = ["AlphaFunction", "BetaFunction"]

    # Regular function with Fn::ToJsonString
    CONFIG_FUNCTION = "ConfigFunction"

    def _get_python_version(self):
        """Get the current Python version in the format expected by Lambda runtimes."""
        return f"python{sys.version_info.major}.{sys.version_info.minor}"

    def test_build_with_foreach_template(self):
        """
        Test that sam build succeeds with a template using Fn::ForEach.

        This test verifies:
        1. Build succeeds with language extensions template (exit code 0)
        2. Expanded functions (AlphaFunction, BetaFunction) are built
        3. Build artifacts exist in .aws-sam/build/ for all functions
        4. ConfigFunction with Fn::ToJsonString is also built
        5. Conditional DeletionPolicy/UpdateReplacePolicy are resolved

        Validates Requirements: 3.1, 3.3, 12.1
        """
        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Run sam build with runtime override
        cmdlist = self.get_command_list(parameter_overrides=overrides)

        LOG.info(f"Running sam build with language extensions template using runtime {runtime}")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify template.yaml exists in build directory
        build_dir_files = os.listdir(str(self.default_build_dir))
        self.assertIn("template.yaml", build_dir_files)

        # Verify expanded functions from Fn::ForEach are built
        # Requirement 3.1: Fn::ForEach is expanded and each generated function is built
        for function_name in self.FOREACH_GENERATED_FUNCTIONS:
            self._verify_function_built(function_name)

        # Verify ConfigFunction with Fn::ToJsonString is built
        self._verify_function_built(self.CONFIG_FUNCTION)

        # Verify conditional DeletionPolicy/UpdateReplacePolicy are resolved in the built template
        self._verify_conditional_policies_resolved()

        LOG.info("Successfully verified all functions were built")

    def test_build_with_foreach_dynamic_codeuri(self):
        """
        Test that sam build succeeds when Fn::ForEach uses dynamic CodeUri with ${FunctionName}.

        This test verifies:
        1. Build succeeds when CodeUri contains ${FunctionName} variable
        2. Each expanded function (AlphaFunction, BetaFunction) uses its own source directory
        3. Build artifacts are created correctly for each function

        Template structure:
        - AlphaFunction -> CodeUri: Alpha/
        - BetaFunction -> CodeUri: Beta/

        Validates Requirements: 3.1, 3.3, 12.1
        """
        # Use the dynamic CodeUri template
        self.template_path = str(Path(self.test_data_path, "language-extensions-dynamic-codeuri", "template.yaml"))

        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Run sam build with runtime override
        cmdlist = self.get_command_list(parameter_overrides=overrides)

        LOG.info(f"Running sam build with dynamic CodeUri template using runtime {runtime}")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify expanded functions from Fn::ForEach are built
        # Each function should have its own source from its respective directory
        for function_name in self.FOREACH_GENERATED_FUNCTIONS:
            self._verify_function_built(function_name)

        LOG.info("Successfully verified dynamic CodeUri functions were built")

    def test_build_dynamic_codeuri_generates_mappings(self):
        """
        Test that sam build with dynamic CodeUri generates Mappings in the output template.

        This test verifies:
        1. Build succeeds with dynamic CodeUri template
        2. The built template contains a Mappings section with SAMCodeUriFunctions
        3. CodeUri is replaced with Fn::FindInMap referencing the Mappings
        4. Each collection value maps to its correct build artifact directory
        5. Fn::ForEach structure is preserved in the output

        Validates Requirements: 6.6, 16.6
        """
        # Use the dynamic CodeUri template
        self.template_path = str(Path(self.test_data_path, "language-extensions-dynamic-codeuri", "template.yaml"))

        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        cmdlist = self.get_command_list(parameter_overrides=overrides)
        command_result = run_command(cmdlist, cwd=self.working_dir)

        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Read the built template
        built_template_path = self.default_build_dir.joinpath("template.yaml")
        self.assertTrue(built_template_path.exists(), "Built template.yaml should exist")

        with open(built_template_path, "r") as f:
            built_template = yaml.safe_load(f)

        # Verify Fn::ForEach structure is preserved
        resources = built_template.get("Resources", {})
        foreach_key = "Fn::ForEach::Functions"
        self.assertIn(foreach_key, resources, "Fn::ForEach::Functions should be preserved in built template")

        foreach_block = resources[foreach_key]
        self.assertIsInstance(foreach_block, list)
        self.assertEqual(len(foreach_block), 3)
        self.assertEqual(foreach_block[0], "FunctionName")
        self.assertEqual(foreach_block[1], ["Alpha", "Beta"])

        # Verify Mappings section was generated
        mappings = built_template.get("Mappings", {})
        mapping_name = "SAMCodeUriFunctions"
        self.assertIn(mapping_name, mappings, f"Built template should contain {mapping_name} Mapping")

        # Verify each collection value has an entry in the Mapping
        mapping_entries = mappings[mapping_name]
        self.assertIn("Alpha", mapping_entries, "Mapping should have entry for Alpha")
        self.assertIn("Beta", mapping_entries, "Mapping should have entry for Beta")

        # Verify each entry has a CodeUri pointing to the build artifact
        alpha_codeuri = mapping_entries["Alpha"].get("CodeUri")
        beta_codeuri = mapping_entries["Beta"].get("CodeUri")
        self.assertIsNotNone(alpha_codeuri, "Alpha should have a CodeUri in Mapping")
        self.assertIsNotNone(beta_codeuri, "Beta should have a CodeUri in Mapping")

        # The build artifact paths should be different (each function has its own source)
        self.assertNotEqual(alpha_codeuri, beta_codeuri, "Alpha and Beta should have different build artifact paths")

        # Verify CodeUri in the ForEach body is replaced with Fn::FindInMap
        body = foreach_block[2]
        function_template = body.get("${FunctionName}Function", {})
        properties = function_template.get("Properties", {})
        codeuri = properties.get("CodeUri")

        self.assertIsInstance(codeuri, dict, "CodeUri should be a dict (Fn::FindInMap)")
        self.assertIn("Fn::FindInMap", codeuri, "CodeUri should use Fn::FindInMap")

        findmap_args = codeuri["Fn::FindInMap"]
        self.assertEqual(findmap_args[0], mapping_name, f"FindInMap should reference {mapping_name}")
        self.assertEqual(findmap_args[1], {"Ref": "FunctionName"}, "FindInMap should use Ref to loop variable")
        self.assertEqual(findmap_args[2], "CodeUri", "FindInMap should look up CodeUri key")

        LOG.info("Successfully verified dynamic CodeUri generates Mappings in build output")

    def test_build_specific_expanded_function(self):
        """
        Test that sam build with function_identifier builds only the specified expanded function.

        This test verifies:
        1. Build succeeds when specifying an expanded function name (AlphaFunction)
        2. Only AlphaFunction is built (not BetaFunction or ConfigFunction)
        3. Build artifacts exist for AlphaFunction in .aws-sam/build/

        Validates Requirements: 3.2
        """
        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Run sam build with function_identifier to build only AlphaFunction
        # This tests the --resource-id functionality (Requirement 3.2)
        target_function = "AlphaFunction"
        cmdlist = self.get_command_list(parameter_overrides=overrides, function_identifier=target_function)

        LOG.info(f"Running sam build for specific function {target_function} using runtime {runtime}")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify template.yaml exists in build directory
        build_dir_files = os.listdir(str(self.default_build_dir))
        self.assertIn("template.yaml", build_dir_files)

        # Verify AlphaFunction was built
        # Requirement 3.2: Build only the specific function when --resource-id is specified
        self._verify_function_built(target_function)

        # Verify BetaFunction was NOT built (only AlphaFunction should be built)
        self.assertNotIn(
            "BetaFunction", build_dir_files, "BetaFunction should NOT be built when building only AlphaFunction"
        )

        # Verify ConfigFunction was NOT built
        self.assertNotIn(
            "ConfigFunction", build_dir_files, "ConfigFunction should NOT be built when building only AlphaFunction"
        )

        LOG.info(f"Successfully verified only {target_function} was built")

    def _verify_function_built(self, function_logical_id: str):
        """
        Verify that a function was built and its artifacts exist.

        Args:
            function_logical_id: The logical ID of the function to verify
        """
        build_dir_files = os.listdir(str(self.default_build_dir))

        # Verify function directory exists in build output
        # Requirement 3.3: Build artifacts exist in .aws-sam/build/
        self.assertIn(
            function_logical_id,
            build_dir_files,
            f"Function {function_logical_id} should have build artifacts in .aws-sam/build/",
        )

        # Verify the function artifact directory exists and contains expected files
        resource_artifact_dir = self.default_build_dir.joinpath(function_logical_id)
        self.assertTrue(
            resource_artifact_dir.exists(), f"Build artifact directory for {function_logical_id} should exist"
        )

        # Verify expected Python files are present
        all_artifacts = set(os.listdir(str(resource_artifact_dir)))
        actual_files = all_artifacts.intersection(self.EXPECTED_FILES_PROJECT_MANIFEST)
        self.assertEqual(
            actual_files,
            self.EXPECTED_FILES_PROJECT_MANIFEST,
            f"Function {function_logical_id} should have expected build artifacts",
        )

        LOG.info(f"Verified function {function_logical_id} was built successfully")

    def test_build_preserves_original_template_with_foreach(self):
        """
        Test that sam build preserves the original Fn::ForEach structure in the built template.

        This test verifies:
        1. Build succeeds with language extensions template
        2. The built template at .aws-sam/build/template.yaml preserves the original Fn::ForEach structure
        3. The expanded functions (AlphaFunction, BetaFunction) are built correctly with artifacts
        4. The built template is suitable for CloudFormation deployment (contains Fn::ForEach)

        Validates Requirements: 6.1, 6.5, 16.1, 16.6
        """
        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Run sam build with runtime override
        cmdlist = self.get_command_list(parameter_overrides=overrides)

        LOG.info(f"Running sam build to verify original template preservation using runtime {runtime}")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        # Requirement 6.1: sam build successfully builds functions generated by Fn::ForEach
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify template.yaml exists in build directory
        built_template_path = self.default_build_dir.joinpath("template.yaml")
        self.assertTrue(built_template_path.exists(), "Built template.yaml should exist")

        # Read the built template
        with open(built_template_path, "r") as f:
            built_template = yaml.safe_load(f)

        # Requirement 6.5, 16.6: Verify the built template preserves the original Fn::ForEach structure
        resources = built_template.get("Resources", {})

        # Check that Fn::ForEach::Functions key exists in Resources (original structure preserved)
        foreach_key = "Fn::ForEach::Functions"
        self.assertIn(
            foreach_key,
            resources,
            f"Built template should preserve original {foreach_key} structure for CloudFormation deployment",
        )

        # Verify the Fn::ForEach structure is correct
        foreach_block = resources[foreach_key]
        self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
        self.assertEqual(len(foreach_block), 3, "Fn::ForEach block should have 3 elements: variable, collection, body")

        # Verify the loop variable
        loop_variable = foreach_block[0]
        self.assertEqual(loop_variable, "FunctionName", "Loop variable should be 'FunctionName'")

        # Verify the collection
        collection = foreach_block[1]
        self.assertIsInstance(collection, list, "Collection should be a list")
        self.assertEqual(collection, ["Alpha", "Beta"], "Collection should contain ['Alpha', 'Beta']")

        # Verify the body template contains the function definition
        body_template = foreach_block[2]
        self.assertIsInstance(body_template, dict, "Body template should be a dict")
        self.assertIn("${FunctionName}Function", body_template, "Body should contain function template")

        # Verify the function template structure
        function_template = body_template["${FunctionName}Function"]
        self.assertEqual(
            function_template.get("Type"),
            "AWS::Serverless::Function",
            "Function template should have correct Type",
        )

        LOG.info("Verified built template preserves original Fn::ForEach structure")

        # Requirement 16.1: Verify expanded functions are built correctly
        # Even though the template preserves Fn::ForEach, the build artifacts should exist
        # for the expanded function names (AlphaFunction, BetaFunction)
        build_dir_files = os.listdir(str(self.default_build_dir))

        for function_name in self.FOREACH_GENERATED_FUNCTIONS:
            self.assertIn(
                function_name,
                build_dir_files,
                f"Expanded function {function_name} should have build artifacts in .aws-sam/build/",
            )

            # Verify the function artifact directory exists and contains expected files
            resource_artifact_dir = self.default_build_dir.joinpath(function_name)
            self.assertTrue(
                resource_artifact_dir.exists(),
                f"Build artifact directory for {function_name} should exist",
            )

            # Verify expected Python files are present
            all_artifacts = set(os.listdir(str(resource_artifact_dir)))
            actual_files = all_artifacts.intersection(self.EXPECTED_FILES_PROJECT_MANIFEST)
            self.assertEqual(
                actual_files,
                self.EXPECTED_FILES_PROJECT_MANIFEST,
                f"Function {function_name} should have expected build artifacts",
            )

            LOG.info(f"Verified expanded function {function_name} was built correctly")

        LOG.info("Successfully verified sam build preserves original template and builds expanded functions")

    def _verify_conditional_policies_resolved(self):
        """
        Verify that conditional DeletionPolicy and UpdateReplacePolicy are resolved in the built template.

        The template uses Fn::If to set DeletionPolicy/UpdateReplacePolicy based on the IsProd condition.

        Note: Since the original template is preserved with Fn::ForEach structure, the expanded function
        names (AlphaFunction, BetaFunction) don't exist directly in the Resources section. Instead, we
        verify that the Fn::ForEach body template and other regular functions have their conditional
        policies preserved (they will be resolved by CloudFormation server-side).
        """
        built_template_path = self.default_build_dir.joinpath("template.yaml")
        self.assertTrue(built_template_path.exists(), "Built template.yaml should exist")

        with open(built_template_path, "r") as f:
            built_template = yaml.safe_load(f)

        resources = built_template.get("Resources", {})

        # Check regular functions (not generated by Fn::ForEach) have DeletionPolicy/UpdateReplacePolicy
        regular_functions = [self.CONFIG_FUNCTION]

        for function_name in regular_functions:
            self.assertIn(function_name, resources, f"Function {function_name} should exist in built template")
            resource = resources[function_name]

            # Check DeletionPolicy exists (it may be Fn::If or resolved string)
            if "DeletionPolicy" in resource:
                deletion_policy = resource["DeletionPolicy"]
                # The policy can be either a string (resolved) or a dict with Fn::If (preserved for CloudFormation)
                if isinstance(deletion_policy, str):
                    self.assertIn(
                        deletion_policy,
                        ["Delete", "Retain", "Snapshot"],
                        f"DeletionPolicy for {function_name} should be a valid policy value",
                    )
                    LOG.info(f"Verified {function_name} DeletionPolicy resolved to: {deletion_policy}")
                elif isinstance(deletion_policy, dict) and "Fn::If" in deletion_policy:
                    LOG.info(f"Verified {function_name} DeletionPolicy preserved as Fn::If for CloudFormation")
                else:
                    self.fail(f"DeletionPolicy for {function_name} has unexpected format: {deletion_policy}")

            # Check UpdateReplacePolicy exists (it may be Fn::If or resolved string)
            if "UpdateReplacePolicy" in resource:
                update_replace_policy = resource["UpdateReplacePolicy"]
                # The policy can be either a string (resolved) or a dict with Fn::If (preserved for CloudFormation)
                if isinstance(update_replace_policy, str):
                    self.assertIn(
                        update_replace_policy,
                        ["Delete", "Retain", "Snapshot"],
                        f"UpdateReplacePolicy for {function_name} should be a valid policy value",
                    )
                    LOG.info(f"Verified {function_name} UpdateReplacePolicy resolved to: {update_replace_policy}")
                elif isinstance(update_replace_policy, dict) and "Fn::If" in update_replace_policy:
                    LOG.info(f"Verified {function_name} UpdateReplacePolicy preserved as Fn::If for CloudFormation")
                else:
                    self.fail(f"UpdateReplacePolicy for {function_name} has unexpected format: {update_replace_policy}")

        # Verify Fn::ForEach block has conditional policies in its body template
        foreach_key = "Fn::ForEach::Functions"
        if foreach_key in resources:
            foreach_block = resources[foreach_key]
            if len(foreach_block) >= 3:
                body_template = foreach_block[2]
                function_template_key = "${FunctionName}Function"
                if function_template_key in body_template:
                    function_template = body_template[function_template_key]
                    # Verify DeletionPolicy exists in the template
                    if "DeletionPolicy" in function_template:
                        LOG.info("Verified Fn::ForEach body template has DeletionPolicy")
                    # Verify UpdateReplacePolicy exists in the template
                    if "UpdateReplacePolicy" in function_template:
                        LOG.info("Verified Fn::ForEach body template has UpdateReplacePolicy")

    def test_build_nested_foreach_dynamic_codeuri_generates_mappings(self):
        """
        Test that sam build with nested Fn::ForEach and dynamic CodeUri generates Mappings.

        Validates Requirements: 25.4, 25.8
        """
        self.template_path = str(
            Path(self.test_data_path, "language-extensions-nested-foreach-dynamic-codeuri", "template.yaml")
        )

        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        cmdlist = self.get_command_list(parameter_overrides=overrides)
        command_result = run_command(cmdlist, cwd=self.working_dir)

        self.assertEqual(
            command_result.process.returncode,
            0,
            f"Build failed with stderr: {command_result.stderr.decode('utf-8')}",
        )

        built_template_path = self.default_build_dir.joinpath("template.yaml")
        self.assertTrue(built_template_path.exists())

        with open(built_template_path, "r") as f:
            built_template = yaml.safe_load(f)

        # Verify nested Fn::ForEach structure is preserved
        resources = built_template.get("Resources", {})
        outer_key = "Fn::ForEach::Environments"
        self.assertIn(outer_key, resources)

        outer_block = resources[outer_key]
        self.assertEqual(outer_block[0], "Env")
        self.assertEqual(outer_block[1], ["dev", "prod"])

        inner_block = outer_block[2]["Fn::ForEach::Services"]
        self.assertEqual(inner_block[0], "Service")
        self.assertEqual(inner_block[1], ["Users", "Orders"])

        # Verify Mappings section was generated
        mappings = built_template.get("Mappings", {})
        self.assertIn("SAMCodeUriEnvironmentsServices", mappings)
        self.assertIn("Users", mappings["SAMCodeUriEnvironmentsServices"])
        self.assertIn("Orders", mappings["SAMCodeUriEnvironmentsServices"])

        # Verify CodeUri replaced with Fn::FindInMap
        inner_body = inner_block[2]
        props = inner_body["${Env}${Service}Function"]["Properties"]
        codeuri = props["CodeUri"]
        self.assertIsInstance(codeuri, dict)
        self.assertIn("Fn::FindInMap", codeuri)
        self.assertEqual(codeuri["Fn::FindInMap"][0], "SAMCodeUriEnvironmentsServices")

        # Verify all expanded functions were built
        for env in ["dev", "prod"]:
            for svc in ["Users", "Orders"]:
                func_dir = self.default_build_dir.joinpath(f"{env}{svc}Function")
                self.assertTrue(func_dir.exists(), f"Build artifact for {env}{svc}Function should exist")


@pytest.mark.python
class TestBuildCommand_LanguageExtensions_NestedStacks(BuildIntegBase):
    """
    Integration tests for sam build with nested stacks using CloudFormation Language Extensions.

    Tests that sam build correctly processes parent templates that reference
    child stacks using AWS::LanguageExtensions with Fn::ForEach.

    Validates Requirements: 10.1, 10.2, 10.3, 13.4
    """

    template = "language-extensions-nested/parent.yaml"

    # Expected files in the build artifact for Python functions
    EXPECTED_FILES_PROJECT_MANIFEST = {
        "__init__.py",
        "main.py",
    }

    # Parent function
    PARENT_FUNCTION = "ParentFunction"

    # Functions generated by Fn::ForEach in child stack
    CHILD_FOREACH_FUNCTIONS = ["ChildAlphaFunction", "ChildBetaFunction"]

    def _get_python_version(self):
        """Get the current Python version in the format expected by Lambda runtimes."""
        return f"python{sys.version_info.major}.{sys.version_info.minor}"

    def test_build_nested_stack_with_language_extensions(self):
        """
        Test that sam build succeeds with nested stacks using language extensions.

        This test verifies:
        1. Build succeeds with parent template referencing child stack with Fn::ForEach
        2. Parent function (ParentFunction) is built
        3. Child functions generated by Fn::ForEach (ChildAlphaFunction, ChildBetaFunction) are built
        4. Build artifacts exist in .aws-sam/build/ for all functions

        Validates Requirements: 10.1, 10.2, 10.3, 13.4
        """
        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Run sam build with runtime override
        cmdlist = self.get_command_list(parameter_overrides=overrides)

        LOG.info(f"Running sam build with nested stacks language extensions template using runtime {runtime}")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify template.yaml exists in build directory
        build_dir_files = os.listdir(str(self.default_build_dir))
        self.assertIn("template.yaml", build_dir_files)

        # Verify parent function is built
        # Requirement 10.1: Parent stack functions are built
        self._verify_function_built(self.PARENT_FUNCTION)

        # Verify child stack directory exists
        # Requirement 10.2: Nested stacks are processed
        self.assertIn("ChildStack", build_dir_files, "ChildStack directory should exist in build output")

        # Verify child functions from Fn::ForEach are built
        # Requirement 10.3: Functions in nested stacks using language extensions are built
        child_stack_dir = self.default_build_dir.joinpath("ChildStack")
        self.assertTrue(child_stack_dir.exists(), "ChildStack build directory should exist")

        child_build_files = os.listdir(str(child_stack_dir))
        for function_name in self.CHILD_FOREACH_FUNCTIONS:
            self.assertIn(
                function_name, child_build_files, f"Child function {function_name} should be built in nested stack"
            )

            # Verify the function artifact directory contains expected files
            function_dir = child_stack_dir.joinpath(function_name)
            self.assertTrue(function_dir.exists(), f"Build artifact directory for {function_name} should exist")

            all_artifacts = set(os.listdir(str(function_dir)))
            actual_files = all_artifacts.intersection(self.EXPECTED_FILES_PROJECT_MANIFEST)
            self.assertEqual(
                actual_files,
                self.EXPECTED_FILES_PROJECT_MANIFEST,
                f"Child function {function_name} should have expected build artifacts",
            )

        LOG.info("Successfully verified nested stack with language extensions was built")

    def _verify_function_built(self, function_logical_id: str):
        """
        Verify that a function was built and its artifacts exist.

        Args:
            function_logical_id: The logical ID of the function to verify
        """
        build_dir_files = os.listdir(str(self.default_build_dir))

        # Verify function directory exists in build output
        self.assertIn(
            function_logical_id,
            build_dir_files,
            f"Function {function_logical_id} should have build artifacts in .aws-sam/build/",
        )

        # Verify the function artifact directory exists and contains expected files
        resource_artifact_dir = self.default_build_dir.joinpath(function_logical_id)
        self.assertTrue(
            resource_artifact_dir.exists(), f"Build artifact directory for {function_logical_id} should exist"
        )

        # Verify expected Python files are present
        all_artifacts = set(os.listdir(str(resource_artifact_dir)))
        actual_files = all_artifacts.intersection(self.EXPECTED_FILES_PROJECT_MANIFEST)
        self.assertEqual(
            actual_files,
            self.EXPECTED_FILES_PROJECT_MANIFEST,
            f"Function {function_logical_id} should have expected build artifacts",
        )

        LOG.info(f"Verified function {function_logical_id} was built successfully")


@pytest.mark.python
class TestBuildCommand_LanguageExtensions_ParameterCollection(BuildIntegBase):
    """
    Integration tests for sam build with Fn::ForEach using parameter reference for collection.

    Tests that sam build correctly processes templates where the Fn::ForEach collection
    is a parameter reference (!Ref FunctionNames) instead of a static list.

    Validates Requirements: 6.1
    """

    template = "language-extensions-param-collection/template.yaml"

    # Expected files in the build artifact for Python functions
    EXPECTED_FILES_PROJECT_MANIFEST = {
        "__init__.py",
        "main.py",
    }

    def _get_python_version(self):
        """Get the current Python version in the format expected by Lambda runtimes."""
        return f"python{sys.version_info.major}.{sys.version_info.minor}"

    def test_build_with_parameter_collection_default_values(self):
        """
        Test that sam build succeeds with Fn::ForEach using parameter reference with default values.

        This test verifies:
        1. Build succeeds when Fn::ForEach collection is !Ref FunctionNames
        2. Default parameter value "Alpha,Beta" is used
        3. Expanded functions (AlphaFunction, BetaFunction) are built correctly
        4. Build artifacts exist in .aws-sam/build/ for all functions

        Validates Requirements: 6.1
        """
        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime}

        # Run sam build with runtime override (uses default FunctionNames="Alpha,Beta")
        cmdlist = self.get_command_list(parameter_overrides=overrides)

        LOG.info(f"Running sam build with parameter collection template using runtime {runtime}")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify template.yaml exists in build directory
        build_dir_files = os.listdir(str(self.default_build_dir))
        self.assertIn("template.yaml", build_dir_files)

        # Verify expanded functions from Fn::ForEach are built
        # Default collection is ["Alpha", "Beta"]
        expected_functions = ["AlphaFunction", "BetaFunction"]
        for function_name in expected_functions:
            self._verify_function_built(function_name)

        LOG.info("Successfully verified build with parameter collection using default values")

    def test_build_with_parameter_collection_override(self):
        """
        Test that sam build succeeds with Fn::ForEach using --parameter-overrides for collection.

        This test verifies:
        1. Build succeeds when FunctionNames parameter is overridden via --parameter-overrides
        2. Overridden value "Alpha,Beta" generates AlphaFunction and BetaFunction
        3. Build artifacts exist in .aws-sam/build/ for all functions

        Validates Requirements: 6.1
        """
        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        # Override FunctionNames parameter with "Alpha,Beta"
        overrides = {"Runtime": runtime, "FunctionNames": "Alpha,Beta"}

        # Run sam build with parameter overrides
        cmdlist = self.get_command_list(parameter_overrides=overrides)

        LOG.info(f"Running sam build with parameter override FunctionNames='Alpha,Beta' using runtime {runtime}")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify template.yaml exists in build directory
        build_dir_files = os.listdir(str(self.default_build_dir))
        self.assertIn("template.yaml", build_dir_files)

        # Verify expanded functions from Fn::ForEach are built
        # Overridden collection is ["Alpha", "Beta"]
        expected_functions = ["AlphaFunction", "BetaFunction"]
        for function_name in expected_functions:
            self._verify_function_built(function_name)

        LOG.info("Successfully verified build with parameter collection override 'Alpha,Beta'")

    def test_build_with_different_parameter_values(self):
        """
        Test that sam build succeeds with different parameter values for the collection.

        This test verifies:
        1. Build succeeds when FunctionNames is overridden with different values
        2. Overridden value "Gamma,Delta,Epsilon" generates GammaFunction, DeltaFunction, EpsilonFunction
        3. Build artifacts exist in .aws-sam/build/ for all functions

        Validates Requirements: 6.1
        """
        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        # Override FunctionNames parameter with "Gamma,Delta,Epsilon"
        overrides = {"Runtime": runtime, "FunctionNames": "Gamma,Delta,Epsilon"}

        # Run sam build with parameter overrides
        cmdlist = self.get_command_list(parameter_overrides=overrides)

        LOG.info(
            f"Running sam build with parameter override FunctionNames='Gamma,Delta,Epsilon' using runtime {runtime}"
        )
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify template.yaml exists in build directory
        build_dir_files = os.listdir(str(self.default_build_dir))
        self.assertIn("template.yaml", build_dir_files)

        # Verify expanded functions from Fn::ForEach are built
        # Overridden collection is ["Gamma", "Delta", "Epsilon"]
        expected_functions = ["GammaFunction", "DeltaFunction", "EpsilonFunction"]
        for function_name in expected_functions:
            self._verify_function_built(function_name)

        LOG.info("Successfully verified build with parameter collection override 'Gamma,Delta,Epsilon'")

    def test_build_preserves_foreach_with_parameter_ref(self):
        """
        Test that sam build preserves the Fn::ForEach structure with parameter reference in built template.

        This test verifies:
        1. Build succeeds with parameter collection template
        2. The built template preserves the Fn::ForEach structure
        3. The collection in the built template is the !Ref FunctionNames (parameter reference)
        4. The expanded functions are built correctly

        Validates Requirements: 6.1
        """
        # Use the current Python version for the runtime
        runtime = self._get_python_version()
        overrides = {"Runtime": runtime, "FunctionNames": "Alpha,Beta"}

        # Run sam build with parameter overrides
        cmdlist = self.get_command_list(parameter_overrides=overrides)

        LOG.info(f"Running sam build to verify Fn::ForEach preservation with parameter ref using runtime {runtime}")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode, 0, f"Build failed with stderr: {command_result.stderr.decode('utf-8')}"
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Verify template.yaml exists in build directory
        built_template_path = self.default_build_dir.joinpath("template.yaml")
        self.assertTrue(built_template_path.exists(), "Built template.yaml should exist")

        # Read the built template
        with open(built_template_path, "r") as f:
            built_template = yaml.safe_load(f)

        # Verify the built template preserves the original Fn::ForEach structure
        resources = built_template.get("Resources", {})

        # Check that Fn::ForEach::Functions key exists in Resources (original structure preserved)
        foreach_key = "Fn::ForEach::Functions"
        self.assertIn(
            foreach_key,
            resources,
            f"Built template should preserve original {foreach_key} structure for CloudFormation deployment",
        )

        # Verify the Fn::ForEach structure is correct
        foreach_block = resources[foreach_key]
        self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
        self.assertEqual(len(foreach_block), 3, "Fn::ForEach block should have 3 elements: variable, collection, body")

        # Verify the loop variable
        loop_variable = foreach_block[0]
        self.assertEqual(loop_variable, "Name", "Loop variable should be 'Name'")

        # Verify the collection is a Ref to FunctionNames parameter
        collection = foreach_block[1]
        # The collection should be preserved as a Ref to the parameter
        self.assertIsInstance(collection, dict, "Collection should be a dict (Ref)")
        self.assertIn("Ref", collection, "Collection should be a Ref to FunctionNames parameter")
        self.assertEqual(collection["Ref"], "FunctionNames", "Collection should reference FunctionNames parameter")

        # Verify the body template contains the function definition
        body_template = foreach_block[2]
        self.assertIsInstance(body_template, dict, "Body template should be a dict")
        self.assertIn("${Name}Function", body_template, "Body should contain function template")

        # Verify the function template structure
        function_template = body_template["${Name}Function"]
        self.assertEqual(
            function_template.get("Type"),
            "AWS::Serverless::Function",
            "Function template should have correct Type",
        )

        LOG.info("Verified built template preserves Fn::ForEach structure with parameter reference")

        # Verify expanded functions are built correctly
        build_dir_files = os.listdir(str(self.default_build_dir))
        expected_functions = ["AlphaFunction", "BetaFunction"]
        for function_name in expected_functions:
            self.assertIn(
                function_name,
                build_dir_files,
                f"Expanded function {function_name} should have build artifacts in .aws-sam/build/",
            )

        LOG.info("Successfully verified sam build preserves Fn::ForEach with parameter reference")

    def _verify_function_built(self, function_logical_id: str):
        """
        Verify that a function was built and its artifacts exist.

        Args:
            function_logical_id: The logical ID of the function to verify
        """
        build_dir_files = os.listdir(str(self.default_build_dir))

        # Verify function directory exists in build output
        self.assertIn(
            function_logical_id,
            build_dir_files,
            f"Function {function_logical_id} should have build artifacts in .aws-sam/build/",
        )

        # Verify the function artifact directory exists and contains expected files
        resource_artifact_dir = self.default_build_dir.joinpath(function_logical_id)
        self.assertTrue(
            resource_artifact_dir.exists(), f"Build artifact directory for {function_logical_id} should exist"
        )

        # Verify expected Python files are present
        all_artifacts = set(os.listdir(str(resource_artifact_dir)))
        actual_files = all_artifacts.intersection(self.EXPECTED_FILES_PROJECT_MANIFEST)
        self.assertEqual(
            actual_files,
            self.EXPECTED_FILES_PROJECT_MANIFEST,
            f"Function {function_logical_id} should have expected build artifacts",
        )

        LOG.info(f"Verified function {function_logical_id} was built successfully")


@pytest.mark.python
class TestBuildCommand_LanguageExtensions_NestedForEachDepthValidation(BuildIntegBase):
    """
    Integration tests for sam build with nested Fn::ForEach depth validation.

    Tests that sam build correctly validates the nesting depth of Fn::ForEach loops
    and fails early with a clear error message when the limit is exceeded.

    Validates Requirements: 18.3, 18.4, 18.5, 18.7
    """

    def test_build_fails_early_on_nested_foreach_depth_exceeded(self):
        """
        Test that sam build fails early when template has 6 levels of nested Fn::ForEach.

        This test verifies:
        1. Build fails before attempting to build any resources
        2. Error message indicates the maximum nesting depth of 5 has been exceeded
        3. Error message indicates the actual nesting depth found (6)
        4. Error is raised during template processing, not during build phase

        Validates Requirements: 18.3, 18.4, 18.5, 18.7
        - 18.3: WHEN a template contains more than 5 levels of nested Fn::ForEach loops,
                THE SAM_CLI SHALL raise an error before processing
        - 18.4: WHEN the nested loop limit is exceeded, THE error message SHALL clearly
                indicate that the maximum nesting depth of 5 has been exceeded
        - 18.5: WHEN the nested loop limit is exceeded, THE error message SHALL indicate
                the actual nesting depth found in the template
        - 18.7: WHEN `sam build` processes a template exceeding the nested loop limit,
                THE Build_Command SHALL fail before attempting to build any resources
        """
        # Use the invalid nested foreach template (6 levels of nesting)
        self.template_path = str(
            Path(self.test_data_path, "language-extensions-nested-foreach-invalid", "template.yaml")
        )

        # Run sam build
        cmdlist = self.get_command_list()

        LOG.info("Running sam build with template that exceeds nested Fn::ForEach depth limit")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Combine stdout and stderr for error message checking
        stdout_output = command_result.stdout.decode("utf-8")
        stderr_output = command_result.stderr.decode("utf-8")
        combined_output = stdout_output + stderr_output

        # Verify build fails (non-zero exit code)
        self.assertNotEqual(
            command_result.process.returncode,
            0,
            f"Expected non-zero exit code but got {command_result.process.returncode}. Output: {combined_output}",
        )

        # Requirement 18.4: Error message indicates maximum nesting depth of 5
        self.assertIn(
            "5",
            combined_output,
            f"Expected error message to mention maximum depth of 5. Actual output: {combined_output}",
        )

        # Requirement 18.5: Error message indicates actual nesting depth found (6)
        self.assertIn(
            "6",
            combined_output,
            f"Expected error message to mention actual depth of 6. Actual output: {combined_output}",
        )

        # Verify the error message mentions nesting or depth
        nesting_indicators = ["nesting", "depth", "exceeds", "maximum", "nested"]
        has_nesting_indicator = any(indicator.lower() in combined_output.lower() for indicator in nesting_indicators)
        self.assertTrue(
            has_nesting_indicator,
            f"Expected error message about nesting depth. Actual output: {combined_output}",
        )

        # Requirement 18.7: Verify build failed early (no build artifacts should be created)
        # If the build directory exists, it should not contain any function artifacts
        if self.default_build_dir.exists():
            build_dir_files = os.listdir(str(self.default_build_dir))
            # The only file that might exist is template.yaml, but no function directories
            function_dirs = [f for f in build_dir_files if f.endswith("Resource") or f.endswith("Function")]
            self.assertEqual(
                len(function_dirs),
                0,
                f"Expected no function artifacts to be built, but found: {function_dirs}",
            )

        LOG.info("Successfully verified sam build fails early on nested Fn::ForEach depth exceeded")


@pytest.mark.python
class TestBuildCommand_LanguageExtensions_DynamicImageUri(BuildIntegBase):
    """
    Integration tests for sam build with Fn::ForEach and dynamic ImageUri.

    Tests that sam build correctly processes templates where Fn::ForEach generates
    container image Lambda functions with dynamic ImageUri.

    Validates Requirements: 6.6, 19.2
    """

    template = "language-extensions-dynamic-imageuri/template.yaml"

    # Functions generated by Fn::ForEach
    FOREACH_GENERATED_FUNCTIONS = ["alphaFunction", "betaFunction"]

    def test_build_with_dynamic_imageuri_generates_mappings(self):
        """
        Test that sam build with dynamic ImageUri generates Mappings in the output template.

        This test verifies:
        1. Build succeeds with dynamic ImageUri template
        2. The built template contains a Mappings section with SAMImageUriFunctions
        3. ImageUri is replaced with Fn::FindInMap referencing the Mappings
        4. Each collection value maps to its correct image
        5. Fn::ForEach structure is preserved in the output

        Validates Requirements: 6.6, 19.2
        """
        import yaml

        # Run sam build
        cmdlist = self.get_command_list()

        LOG.info("Running sam build with dynamic ImageUri template")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds (exit code 0)
        self.assertEqual(
            command_result.process.returncode,
            0,
            f"Build failed with stderr: {command_result.stderr.decode('utf-8')}",
        )

        # Verify build directory was created
        self.assertTrue(self.default_build_dir.exists(), "Build directory should be created")

        # Read the built template
        built_template_path = self.default_build_dir.joinpath("template.yaml")
        self.assertTrue(built_template_path.exists(), "Built template.yaml should exist")

        with open(built_template_path, "r") as f:
            built_template = yaml.safe_load(f)

        # Verify Fn::ForEach structure is preserved
        resources = built_template.get("Resources", {})
        foreach_key = "Fn::ForEach::Functions"
        self.assertIn(foreach_key, resources, "Fn::ForEach::Functions should be preserved in built template")

        foreach_block = resources[foreach_key]
        self.assertIsInstance(foreach_block, list)
        self.assertEqual(len(foreach_block), 3)
        self.assertEqual(foreach_block[0], "FunctionName")
        self.assertEqual(foreach_block[1], ["alpha", "beta"])

        # Verify Mappings section was generated
        mappings = built_template.get("Mappings", {})
        mapping_name = "SAMImageUriFunctions"
        self.assertIn(mapping_name, mappings, f"Built template should contain {mapping_name} Mapping")

        # Verify each collection value has an entry in the Mapping
        mapping_entries = mappings[mapping_name]
        self.assertIn("alpha", mapping_entries, "Mapping should have entry for alpha")
        self.assertIn("beta", mapping_entries, "Mapping should have entry for beta")

        # Verify each entry has an ImageUri
        alpha_imageuri = mapping_entries["alpha"].get("ImageUri")
        beta_imageuri = mapping_entries["beta"].get("ImageUri")
        self.assertIsNotNone(alpha_imageuri, "alpha should have an ImageUri in Mapping")
        self.assertIsNotNone(beta_imageuri, "beta should have an ImageUri in Mapping")

        # The image URIs should be different (each function has its own image)
        self.assertNotEqual(alpha_imageuri, beta_imageuri, "alpha and beta should have different ImageUri values")

        # Verify ImageUri in the ForEach body is replaced with Fn::FindInMap
        body = foreach_block[2]
        function_template = body.get("${FunctionName}Function", {})
        properties = function_template.get("Properties", {})
        imageuri = properties.get("ImageUri")

        self.assertIsInstance(imageuri, dict, "ImageUri should be a dict (Fn::FindInMap)")
        self.assertIn("Fn::FindInMap", imageuri, "ImageUri should use Fn::FindInMap")

        findmap_args = imageuri["Fn::FindInMap"]
        self.assertEqual(findmap_args[0], mapping_name, f"FindInMap should reference {mapping_name}")
        self.assertEqual(findmap_args[1], {"Ref": "FunctionName"}, "FindInMap should use Ref to loop variable")
        self.assertEqual(findmap_args[2], "ImageUri", "FindInMap should look up ImageUri key")

        LOG.info("Successfully verified dynamic ImageUri generates Mappings in build output")

    def test_build_preserves_foreach_structure_with_dynamic_imageuri(self):
        """
        Test that sam build preserves the original Fn::ForEach structure with dynamic ImageUri.

        This test verifies:
        1. Build succeeds with dynamic ImageUri template
        2. The built template preserves the Fn::ForEach structure
        3. The template is suitable for CloudFormation deployment

        Validates Requirements: 6.5, 16.6
        """
        import yaml

        # Run sam build
        cmdlist = self.get_command_list()

        LOG.info("Running sam build to verify Fn::ForEach preservation with dynamic ImageUri")
        command_result = run_command(cmdlist, cwd=self.working_dir)

        # Verify build succeeds
        self.assertEqual(
            command_result.process.returncode,
            0,
            f"Build failed with stderr: {command_result.stderr.decode('utf-8')}",
        )

        # Read the built template
        built_template_path = self.default_build_dir.joinpath("template.yaml")
        with open(built_template_path, "r") as f:
            built_template = yaml.safe_load(f)

        # Verify Fn::ForEach structure is preserved
        resources = built_template.get("Resources", {})
        foreach_key = "Fn::ForEach::Functions"

        self.assertIn(
            foreach_key,
            resources,
            "Built template should preserve Fn::ForEach::Functions structure",
        )

        # Verify the Fn::ForEach structure is correct
        foreach_block = resources[foreach_key]
        self.assertIsInstance(foreach_block, list, "Fn::ForEach block should be a list")
        self.assertEqual(len(foreach_block), 3, "Fn::ForEach block should have 3 elements")

        # Verify the loop variable
        loop_variable = foreach_block[0]
        self.assertEqual(loop_variable, "FunctionName", "Loop variable should be 'FunctionName'")

        # Verify the collection
        collection = foreach_block[1]
        self.assertEqual(collection, ["alpha", "beta"], "Collection should be ['alpha', 'beta']")

        # Verify the body template contains the function definition
        body_template = foreach_block[2]
        self.assertIn("${FunctionName}Function", body_template, "Body should contain function template")

        # Verify the function template structure
        function_template = body_template["${FunctionName}Function"]
        self.assertEqual(
            function_template.get("Type"),
            "AWS::Serverless::Function",
            "Function template should have correct Type",
        )

        # Verify PackageType is Image
        properties = function_template.get("Properties", {})
        self.assertEqual(
            properties.get("PackageType"),
            "Image",
            "PackageType should be Image",
        )

        LOG.info("Successfully verified Fn::ForEach structure is preserved with dynamic ImageUri")
