"""
Integration tests for sam local start-api with CloudFormation Language Extensions.

Tests that sam local start-api can serve API endpoints generated by Fn::ForEach expansion.
"""

import sys
from pathlib import Path

import pytest
import requests

from .start_api_integ_base import StartApiIntegBaseClass
from tests.testing_utils import get_sam_command, run_command


class TestStartApiLanguageExtensions(StartApiIntegBaseClass):
    """Integration tests for sam local start-api with Fn::ForEach-expanded endpoints."""

    template_path = "/testdata/start_api/language-extensions-api.yaml"
    build_before_invoke = True

    @classmethod
    def setUpClass(cls):
        python_version = f"python{sys.version_info.major}.{sys.version_info.minor}"
        cls.parameter_overrides = {"Runtime": python_version}
        cls.build_overrides = {"Runtime": python_version}
        super().setUpClass()

    @classmethod
    def build(cls):
        command = get_sam_command()
        command_list = [command, "build", "--language-extensions"]
        if cls.build_overrides:
            overrides_arg = " ".join(
                ["ParameterKey={},ParameterValue={}".format(key, value) for key, value in cls.build_overrides.items()]
            )
            command_list += ["--parameter-overrides", overrides_arg]
        working_dir = str(Path(cls.template).resolve().parents[0])
        run_command(command_list, cwd=working_dir)

    def setUp(self):
        self.url = f"http://127.0.0.1:{self.port}"

    @pytest.mark.flaky(reruns=3)
    @pytest.mark.tier1_extra
    @pytest.mark.timeout(timeout=600, method="thread")
    def test_foreach_expanded_endpoint(self):
        """Test that an endpoint generated by Fn::ForEach is served correctly."""
        response = requests.get(f"{self.url}/alpha", timeout=300)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json(), {"hello": "world"})
