"""
Integration tests for sam local start-api with CloudFormation Language Extensions.

Tests that sam local start-api can serve API endpoints generated by Fn::ForEach expansion.
"""

import sys

import pytest
import requests

from .start_api_integ_base import StartApiIntegBaseClass


class TestStartApiLanguageExtensions(StartApiIntegBaseClass):
    """Integration tests for sam local start-api with Fn::ForEach-expanded endpoints."""

    template_path = "/testdata/start_api/language-extensions-api.yaml"

    @classmethod
    def setUpClass(cls):
        python_version = f"python{sys.version_info.major}.{sys.version_info.minor}"
        cls.parameter_overrides = {"Runtime": python_version}
        super().setUpClass()

    def setUp(self):
        self.url = f"http://127.0.0.1:{self.port}"

    @pytest.mark.flaky(reruns=3)
    @pytest.mark.tier1_extra
    @pytest.mark.timeout(timeout=600, method="thread")
    def test_foreach_expanded_endpoint(self):
        """Test that an endpoint generated by Fn::ForEach is served correctly."""
        response = requests.get(f"{self.url}/alpha", timeout=300)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json(), {"hello": "world"})
