"""
Integration tests for sam local start-api with CloudFormation Language Extensions.

Tests verify that sam local start-api can serve API endpoints generated by Fn::ForEach
expansion from templates using AWS::LanguageExtensions transform.

Requirements:
- 5.1: WHEN `sam local start-api` processes a template with `Fn::ForEach` generating
       API Gateway resources, THE Start_API_Command SHALL serve all expanded API endpoints
- 5.2: WHEN an API endpoint is generated by `Fn::ForEach` with a path like `/alpha` and `/beta`,
       THE Start_API_Command SHALL route requests to the correct expanded function
- 12.5: THE Integration_Tests SHALL verify `sam local start-api` serves API endpoints
        generated by `Fn::ForEach`
"""

import sys

import pytest
import requests

from .start_api_integ_base import StartApiIntegBaseClass


class TestStartApiLanguageExtensions(StartApiIntegBaseClass):
    """
    Integration tests for sam local start-api with CloudFormation Language Extensions.

    This test class verifies that API endpoints generated by Fn::ForEach expansion
    can be served using sam local start-api.
    """

    template_path = "/testdata/start_api/language-extensions-api.yaml"

    @classmethod
    def setUpClass(cls):
        # Set parameter overrides to use current Python version
        python_version = f"python{sys.version_info.major}.{sys.version_info.minor}"
        cls.parameter_overrides = {"Runtime": python_version}
        super().setUpClass()

    def setUp(self):
        self.url = f"http://127.0.0.1:{self.port}"

    @pytest.mark.flaky(reruns=3)
    @pytest.mark.timeout(timeout=600, method="thread")
    def test_foreach_expanded_alpha_endpoint(self):
        """
        Test that the /alpha endpoint generated by Fn::ForEach is served correctly.

        This test verifies:
        1. The /alpha endpoint is accessible
        2. The alphaFunction is invoked
        3. The response is correct

        Validates: Requirements 5.1, 5.2, 12.5
        """
        response = requests.get(f"{self.url}/alpha", timeout=300)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json(), {"hello": "world"})

    @pytest.mark.flaky(reruns=3)
    @pytest.mark.timeout(timeout=600, method="thread")
    def test_foreach_expanded_beta_endpoint(self):
        """
        Test that the /beta endpoint generated by Fn::ForEach is served correctly.

        This test verifies:
        1. The /beta endpoint is accessible
        2. The betaFunction is invoked
        3. The response is correct

        Validates: Requirements 5.1, 5.2, 12.5
        """
        response = requests.get(f"{self.url}/beta", timeout=300)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json(), {"hello": "world"})

    @pytest.mark.flaky(reruns=3)
    @pytest.mark.timeout(timeout=600, method="thread")
    def test_both_foreach_endpoints_accessible(self):
        """
        Test that both /alpha and /beta endpoints are accessible in the same session.

        This test verifies that all ForEach-expanded endpoints are served simultaneously.

        Validates: Requirements 5.1, 12.5
        """
        alpha_response = requests.get(f"{self.url}/alpha", timeout=300)
        beta_response = requests.get(f"{self.url}/beta", timeout=300)

        self.assertEqual(alpha_response.status_code, 200)
        self.assertEqual(beta_response.status_code, 200)
        self.assertEqual(alpha_response.json(), {"hello": "world"})
        self.assertEqual(beta_response.json(), {"hello": "world"})
