"""Lambda handler for functions generated by Fn::ForEach with parameter collection.

This handler is shared by all functions generated from the FunctionNames parameter.
Each function receives its name via the FUNCTION_NAME environment variable.
"""

import os


def handler(event, context):
    """Lambda handler that returns information about the function.
    
    Args:
        event: Lambda event data
        context: Lambda context object
        
    Returns:
        dict: Response with function information
    """
    function_name = os.environ.get("FUNCTION_NAME", "Unknown")
    
    return {
        "statusCode": 200,
        "body": {
            "message": f"Hello from {function_name}",
            "function": f"{function_name}Function",
            "source": "parameter-collection-template"
        }
    }
