AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Go Lambda function 

Resources:

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./main.zip
      Runtime: go1.x
