name: Test the integration between SAM CLI and Latest CDK version

on:
  schedule:
    - cron: "0 13 * * 1-5" # run 1PM UTC (6 am PDT) in every weekday
  workflow_dispatch: {}

# to automatically cancel the running workflow for same PR.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name:  Integration Tests / ${{ matrix.python }}
    if: github.repository == 'aws/aws-sam-cli'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      SAM_CLI_DEV: 1
      NOSE_PARAMETERIZED_NO_WARN: 1
      APPVEYOR_CONSOLE_DISABLE_PTY: false
      APPVEYOR_DETAILED_SHELL_LOGGING: true
    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          # set last version as the one in matrix to make it default
          python-version: |
            3.9
            ${{ matrix.python }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Init samdev
        run: make init
      - name: Run CDK integration tests
        run: pytest -vv tests/iac_integration
