name: "Close stale issues"

# Controls when the action will run.
on:
  schedule:
  - cron: "0 6 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: aws-actions/stale-issue-cleanup@v3
      with:
        issue-types: issues
      
        # Setting messages to an empty string will cause the automation to skip
        # that category
        ancient-issue-message: This issue has not received any attention in 1 year. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-issue-message: This issue has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-pr-message: This PR has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.

        # These labels are required
        stale-issue-label: blocked/close-if-inactive
        exempt-issue-labels: no-autoclose, stage/need-attention
        stale-pr-label: blocked/close-if-inactive
        exempt-pr-labels: no-autoclose, type/feature
        response-requested-label: blocked/more-info-needed

        # Don't set this to not apply a label when closing issues
        closed-for-staleness-label: closed-for-inactive

        # Issue timing
        days-before-stale: 14
        days-before-close: 7
        days-before-ancient: 365

        # If you don't want to mark a issue as being ancient based on a
        # threshold of "upvotes", you can set this here. An "upvote" is
        # the total number of +1, heart, hooray, and rocket reactions
        # on an issue.
        minimum-upvotes-to-exempt: 10

        # need a repo scope token here to make this action can trigger other github actions
        repo-token: ${{ secrets.REPO_SCOPED_TOKEN }}
        #loglevel: DEBUG
        # Set dry-run to true to not perform label or close actions.
        #dry-run: true
