name: Slack Notifications

on:
  issues:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Send New Issue Notification
        if: github.event_name == 'issues'
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'Issue Created: ${{ github.event.issue.title }} by ${{ github.event.issue.user.login }}'
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
          SLACK_MESSAGE: '${{ github.event.issue.html_url }}'
