name: Check PR title
on:
  pull_request:
    types: [opened, edited]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          title=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
          if [[ ! $title =~ ^.*:\ .*$ ]]; then
            echo "Pull request titles must adhere to Conventional Commits: https://www.conventionalcommits.org"
            exit 1
          fi
