name: Check PR title
on:
  pull_request:
    types: [opened, edited]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check PR title
        run: |
          title=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
          [[ $title =~ ^.*:\ .*$ ]] || exit 1
