name: Update aws/aws-sam-cli with latest commit hash from aws/aws-sam-cli-app-templates

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  updateCommitHash:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Templates
        uses: actions/checkout@v3
        with:
          repository: aws/aws-sam-cli-app-templates
          path: aws-sam-cli-app-templates

      - name: Checkout SAM CLI
        uses: actions/checkout@v3
        with:
          repository: aws/aws-sam-cli
          path: aws-sam-cli

      - name: Update commit hash in SAM CLI from App Templates
        run: |
          cd aws-sam-cli-app-templates
          export APP_TEMPLATES_COMMIT_HASH=$(git rev-parse HEAD)
          cd ../aws-sam-cli
          cat <<< $(jq --arg commit_hash "$APP_TEMPLATES_COMMIT_HASH" --indent 4 '.app_template_repo_commit =  $commit_hash' samcli/runtime_config.json) > samcli/runtime_config.json

      - name: Raise PR for SAM CLI
        uses: peter-evans/create-pull-request@v4
        with:
          path: aws-sam-cli
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update_app_templates_hash
          delete-branch: true
          title: 'feat: update SAM CLI with latest App Templates commit hash'
          body:
            This PR & commit is automatically created by GH action to update the aws/aws-sam-cli with latest hash of the aws/aws-sam-cli-app-templates.
